// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/activity/enrichments.proto

/* eslint-disable */

export const protobufPackage = "fitglue.models.activity";

export enum StreakDayState {
  STREAK_DAY_STATE_UNSPECIFIED = 0,
  /** STREAK_DAY_STATE_OFF - no qualifying activity */
  STREAK_DAY_STATE_OFF = 1,
  /** STREAK_DAY_STATE_ACTIVE - active training day */
  STREAK_DAY_STATE_ACTIVE = 2,
  /** STREAK_DAY_STATE_REST - scheduled rest; counts toward streak */
  STREAK_DAY_STATE_REST = 3,
  UNRECOGNIZED = -1,
}

/**
 * ActivityEnrichments holds typed outputs from the enricher pipeline.
 * Each sub-message is optional — only present if the corresponding enricher
 * was configured and ran. Replaces enrichment_metadata map<string,string>.
 */
export interface ActivityEnrichments {
  heartRate?: HeartRateSummary | undefined;
  heartRateZones?: HeartRateZonesSummary | undefined;
  effort?: EffortScoreSummary | undefined;
  calories?: CaloriesSummary | undefined;
  trainingLoad?: TrainingLoadSummary | undefined;
  recovery?: RecoverySummary | undefined;
  streak?: StreakSummary | undefined;
  aiSummary?: AiSummary | undefined;
  aiBanner?: AiBanner | undefined;
  pace?: PaceSummary | undefined;
  cadence?: CadenceSummary | undefined;
  power?: PowerSummary | undefined;
  elevation?: ElevationSummary | undefined;
  speed?: SpeedSummary | undefined;
  parkrun?: ParkrunSummary | undefined;
  weather?: WeatherSummary | undefined;
  location?: LocationSummary | undefined;
  runningDynamics?: RunningDynamicsSummary | undefined;
  personalRecords?: PersonalRecordsSummary | undefined;
  distanceMilestone?: DistanceMilestoneSummary | undefined;
  goalTracker?: GoalTrackerSummary | undefined;
  spotify?: SpotifyTracksSummary | undefined;
  intervals?: IntervalsSummary | undefined;
  muscleHeatmap?: MuscleHeatmapSummary | undefined;
}

export interface HeartRateSummary {
  minBpm: number;
  avgBpm: number;
  maxBpm: number;
  /** positive means HR drifted up over the session */
  driftBpm: number;
  /** true if drift exceeds the enricher's configured threshold */
  driftWarning: boolean;
}

export interface HeartRateZonesSummary {
  zones: HeartRateZoneBucket[];
  totalMinutes: number;
}

export interface HeartRateZoneBucket {
  /** 0–5 */
  zoneIndex: number;
  /** "Zone 0 (Rest)", "Zone 1 (Recovery)", … */
  name: string;
  minutes: number;
  percentage: number;
}

export interface EffortScoreSummary {
  /** 0–100 relative to user's rolling history */
  score: number;
  /** "Easy", "Moderate", "Hard", "Very Hard" */
  band: string;
  factors: EffortFactor[];
}

export interface EffortFactor {
  /** "HR", "Pace", "Duration", "Elevation", "Intensity" */
  label: string;
  /** e.g. 0.75, 1.21 */
  ratioVsBaseline: number;
}

export interface CaloriesSummary {
  kcal: number;
  /** e.g. "≈ 1.0 slice of pizza" */
  comparisonText: string;
}

export interface TrainingLoadSummary {
  trimp: number;
  /** "Recovery", "Easy", "Moderate", "Hard", "Very Hard" */
  bucket: string;
  /** short contextual copy */
  hint: string;
}

export interface RecoverySummary {
  /** TRIMP for this session */
  sessionLoad: number;
  /** ACWR */
  acuteChronicRatio: number;
  hoursToRecover: number;
  /** true if ACWR is in the danger band (> 1.3) */
  alert: boolean;
  /** e.g. "ACWR 1.42 — load is climbing fast" */
  alertText: string;
}

export interface StreakSummary {
  currentDays: number;
  longestDays: number;
  /** most-recent-last; covers last N days */
  calendar: StreakDay[];
}

export interface StreakDay {
  /** YYYY-MM-DD */
  date: string;
  state: StreakDayState;
}

export interface AiSummary {
  /** sanitised HTML — may contain <b> and <span> */
  html: string;
  /** e.g. "gemini-1.5-flash" */
  model: string;
  generatedAt?: Date | undefined;
}

export interface AiBanner {
  /** CDN URL */
  imageUrl: string;
  /** for cache-busting */
  promptHash: string;
  generatorVersion: string;
}

export interface PaceSummary {
  avgPaceSecondsPerKm: number;
  bestSplitSecondsPerKm: number;
  splits: PaceSplit[];
}

export interface PaceSplit {
  km: number;
  seconds: number;
}

export interface CadenceSummary {
  avgRpm: number;
  maxRpm: number;
}

export interface PowerSummary {
  avgWatts: number;
  /** NP */
  normalizedPower: number;
  /** IF */
  intensityFactor: number;
  kilojoules: number;
}

export interface ElevationSummary {
  totalGainM: number;
  totalLossM: number;
}

export interface SpeedSummary {
  avgSpeedKmh: number;
  maxSpeedKmh: number;
}

export interface WeatherSummary {
  tempC: number;
  /** "Clear", "Rain", "Partly Cloudy", etc. */
  weatherDescription: string;
  windSpeedKph: number;
  /** "N", "NE", "SW", etc. */
  windDirection: string;
  /** WMO weather code */
  weatherCode: number;
}

export interface LocationSummary {
  /** e.g. "Bushy Park, London" */
  locationName: string;
  country: string;
  latitude: number;
  longitude: number;
}

export interface RunningDynamicsSummary {
  avgGroundContactMs: number;
  avgVerticalOscillationCm: number;
  avgStepLengthM: number;
}

export interface ParkrunSummary {
  /** e.g. "Bushy parkrun" */
  eventName: string;
  position: number;
  /** e.g. "19:42" */
  finishTime: string;
  /** e.g. "76.2%" */
  ageGrade: string;
  /** all-time run count */
  totalParkruns: number;
  isTimePb: boolean;
  isAgeGradePb: boolean;
}

export interface PersonalRecord {
  /** e.g. "5k", "bench_press_1rm" */
  recordType: string;
  newValue: number;
  /** "seconds", "kg" */
  unit: string;
  previousValue?:
    | number
    | undefined;
  /** percentage */
  improvement?:
    | number
    | undefined;
  /** formatted human-readable summary */
  displayMessage: string;
}

export interface PersonalRecordsSummary {
  records: PersonalRecord[];
}

export interface DistanceMilestoneSummary {
  milestoneKm: number;
  lifetimeDistanceKm: number;
  nextMilestoneKm?:
    | number
    | undefined;
  /** e.g. "running" */
  activityTypeLabel: string;
}

export interface GoalEntry {
  /** e.g. "Run · 2,500 km" */
  label: string;
  /** accumulated progress this period */
  current: number;
  target: number;
  /** "km", "hours", "activities" */
  unit: string;
  onPace: boolean;
  daysRemaining: number;
}

export interface GoalTrackerSummary {
  goals: GoalEntry[];
}

export interface SpotifyTrack {
  title: string;
  artist: string;
  durationSeconds: number;
}

export interface SpotifyTracksSummary {
  tracks: SpotifyTrack[];
  totalCount: number;
}

export interface IntervalSegment {
  /** "warmup", "active", "recovery", "cooldown" */
  type: string;
  /** e.g. "Interval 1", "Recovery 2" */
  label: string;
  durationSeconds: number;
  distanceMeters: number;
  avgHr: number;
  /** m/s — derive pace/speed from activity category */
  avgSpeedMs: number;
}

export interface IntervalsSummary {
  segments: IntervalSegment[];
  /** e.g. "4×400m" if structured workout */
  workoutName: string;
}

export interface MuscleHeatmapSummary {
  /** e.g. ["chest", "triceps"] */
  primary: string[];
  /** e.g. ["shoulders"] */
  secondary: string[];
  /** populated by MUSCLE_HEATMAP_IMAGE if it ran */
  imageUrl: string;
}
