// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/activity/roundup.proto

/* eslint-disable */
import type { ActivitySource, ActivityType } from "./source";
import type { ShowcaseTopPR } from "./uploaded";

export const protobufPackage = "fitglue.models.activity";

export enum RoundupPeriodType {
  ROUNDUP_PERIOD_TYPE_UNSPECIFIED = 0,
  ROUNDUP_PERIOD_TYPE_WEEK = 1,
  ROUNDUP_PERIOD_TYPE_MONTH = 2,
  ROUNDUP_PERIOD_TYPE_YEAR = 3,
  UNRECOGNIZED = -1,
}

/** Per-day effort record for the consistency calendar heatmap. */
export interface RoundupDayEntry {
  /** YYYY-MM-DD (UTC) */
  date: string;
  /** 0=rest 1=easy 2=moderate 3=hard 4=peak */
  effortLevel: number;
  activityCount: number;
}

/** Pre-computed spotlight card — biggest session, longest streak, peak PR day. */
export interface ShowcaseCalloutActivity {
  /** e.g. "BIGGEST SESSION" */
  kind: string;
  title: string;
  /** pre-formatted primary stat, e.g. "5:42" */
  statValue: string;
  /** unit/sub-stat line, e.g. "H:MM · 142 KM" */
  statUnit: string;
  /** second detail line */
  sub: string;
  /** e.g. "14 Sep" */
  date: string;
  activityType: ActivityType;
}

/** A photo surfaced in the roundup photo mosaic. */
export interface RoundupPhoto {
  url: string;
  activityTitle: string;
  /** e.g. "14 Sep" */
  date: string;
  activityType: ActivityType;
}

/** A GPS route thumbnail surfaced in the roundup route wall. */
export interface RoundupRoute {
  thumbnailUrl: string;
  activityTitle: string;
  /** e.g. "14 Sep" */
  date: string;
  distanceMeters: number;
  activityType: ActivityType;
}

export interface RoundupActivityTypeBreakdown {
  activityType: ActivityType;
  activityCount: number;
  totalDistanceMeters: number;
  totalDurationSeconds: number;
  totalWeightKg: number;
  totalSets: number;
  totalReps: number;
}

export interface ShowcaseRoundup {
  roundupId: string;
  slug: string;
  userId: string;
  periodType: RoundupPeriodType;
  periodKey: string;
  periodStart?: Date | undefined;
  periodEnd?: Date | undefined;
  generatedAt?: Date | undefined;
  totalActivities: number;
  totalDurationSeconds: number;
  totalDistanceMeters: number;
  totalElevationGainMeters: number;
  totalCaloriesKcal: number;
  activityTypeBreakdowns: RoundupActivityTypeBreakdown[];
  hrZoneMinutes: number[];
  prsAchieved: ShowcaseTopPR[];
  sources: ActivitySource[];
  effortEasyCount: number;
  effortModerateCount: number;
  effortHardCount: number;
  ownerDisplayName: string;
  ownerProfilePictureUrl: string;
  ownerProfileSlug: string;
  /** Highlight stats — best single activity across the period */
  longestActivityDurationSeconds: number;
  highestSingleLiftKg: number;
  highestCaloriesPerHourKcal: number;
  highestAvgBpmActivityTitle: string;
  highestAvgBpm: number;
  /** AI-generated narrative summary of the period, empty if unavailable */
  aiSummary: string;
  /** Pre-computed spotlight callouts (biggest session, longest streak, peak PR day) */
  calloutActivities: ShowcaseCalloutActivity[];
  /** Per-day effort entries for the consistency calendar heatmap */
  dayEntries: RoundupDayEntry[];
  /** Photos collected from the period's activities (gated by show_photo_gallery) */
  photos: RoundupPhoto[];
  /** GPS route thumbnails collected from the period's activities */
  routes: RoundupRoute[];
}
