// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/activity/standardized.proto

/* eslint-disable */
import type { ActivitySource, ActivityType } from "./source";

export const protobufPackage = "fitglue.models.activity";

export enum MuscleGroup {
  MUSCLE_GROUP_UNSPECIFIED = 0,
  MUSCLE_GROUP_ABDOMINALS = 1,
  MUSCLE_GROUP_SHOULDERS = 2,
  MUSCLE_GROUP_BICEPS = 3,
  MUSCLE_GROUP_TRICEPS = 4,
  MUSCLE_GROUP_FOREARMS = 5,
  MUSCLE_GROUP_QUADRICEPS = 6,
  MUSCLE_GROUP_HAMSTRINGS = 7,
  MUSCLE_GROUP_CALVES = 8,
  MUSCLE_GROUP_GLUTES = 9,
  MUSCLE_GROUP_ABDUCTORS = 10,
  MUSCLE_GROUP_ADDUCTORS = 11,
  MUSCLE_GROUP_LATS = 12,
  MUSCLE_GROUP_UPPER_BACK = 13,
  MUSCLE_GROUP_TRAPS = 14,
  MUSCLE_GROUP_LOWER_BACK = 15,
  MUSCLE_GROUP_CHEST = 16,
  MUSCLE_GROUP_CARDIO = 17,
  MUSCLE_GROUP_NECK = 18,
  MUSCLE_GROUP_FULL_BODY = 19,
  MUSCLE_GROUP_OTHER = 20,
  UNRECOGNIZED = -1,
}

export interface StandardizedActivity {
  source: ActivitySource;
  externalId: string;
  userId: string;
  startTime?: Date | undefined;
  name: string;
  type: ActivityType;
  sessions: Session[];
  description: string;
  tags: string[];
  notes: string;
  timeMarkers: TimeMarker[];
  workout?: WorkoutDefinition | undefined;
}

export interface TimeMarker {
  timestamp?: Date | undefined;
  label: string;
  markerType: string;
}

export interface Session {
  startTime?: Date | undefined;
  totalElapsedTime: number;
  totalDistance: number;
  laps: Lap[];
  strengthSets: StrengthSet[];
  totalCalories?: number | undefined;
  avgHeartRate?: number | undefined;
  maxHeartRate?: number | undefined;
}

export interface Lap {
  startTime?: Date | undefined;
  totalElapsedTime: number;
  totalDistance: number;
  records: Record[];
  exerciseName: string;
  intensity: string;
}

export interface Record {
  timestamp?: Date | undefined;
  heartRate: number;
  power: number;
  cadence: number;
  speed: number;
  altitude: number;
  positionLat: number;
  positionLong: number;
  groundContactTime?: number | undefined;
  verticalOscillation?: number | undefined;
  verticalRatio?: number | undefined;
  stepLength?: number | undefined;
}

export interface StrengthSet {
  exerciseName: string;
  reps: number;
  weightKg: number;
  startTime?: Date | undefined;
  durationSeconds: number;
  notes: string;
  supersetId: string;
  primaryMuscleGroup: MuscleGroup;
  secondaryMuscleGroups: MuscleGroup[];
  distanceMeters: number;
  setType: string;
}

export interface WorkoutDefinition {
  name: string;
  steps: WorkoutStep[];
}

export interface WorkoutStep {
  intensity: string;
  durationType: string;
  durationValue: number;
  targetType: string;
  targetLow: number;
  targetHigh: number;
}
