// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/activity/uploaded.proto

/* eslint-disable */
import type { DestinationType } from "../plugin/provider";
import type { ActivityEnrichments, BestEffort, HeartRateZoneBucket } from "./enrichments";
import type { ActivitySource, ActivityType } from "./source";
import type { StandardizedActivity } from "./standardized";

export const protobufPackage = "fitglue.models.activity";

/**
 * ShowcaseViewTarget identifies which kind of public showcase surface a view
 * metric belongs to. Used by the owner-facing stats read path.
 */
export enum ShowcaseViewTarget {
  SHOWCASE_VIEW_TARGET_UNSPECIFIED = 0,
  /** SHOWCASE_VIEW_TARGET_ACTIVITY - a single showcased activity page */
  SHOWCASE_VIEW_TARGET_ACTIVITY = 1,
  /** SHOWCASE_VIEW_TARGET_PROFILE - the athlete's profile page */
  SHOWCASE_VIEW_TARGET_PROFILE = 2,
  /** SHOWCASE_VIEW_TARGET_ROUNDUP - a roundup page */
  SHOWCASE_VIEW_TARGET_ROUNDUP = 3,
  UNRECOGNIZED = -1,
}

export interface UploadedActivityRecord {
  id: string;
  userId: string;
  source: ActivitySource;
  externalId: string;
  startTime?: Date | undefined;
  destination: DestinationType;
  destinationId: string;
  uploadedAt?: Date | undefined;
}

/** ShowcasedActivity represents a publicly shareable activity snapshot. */
export interface ShowcasedActivity {
  showcaseId: string;
  activityId: string;
  title: string;
  description: string;
  activityType: ActivityType;
  source: ActivitySource;
  startTime?: Date | undefined;
  activityData?: StandardizedActivity | undefined;
  fitFileUri: string;
  appliedEnrichments: string[];
  tags: string[];
  pipelineExecutionId?: string | undefined;
  createdAt?: Date | undefined;
  expiresAt?: Date | undefined;
  ownerDisplayName: string;
  activityDataUri: string;
  ownerProfilePictureUrl: string;
  ownerProfileSlug: string;
  photoUrls: string[];
  enrichments?: ActivityEnrichments | undefined;
}

export interface ShowcaseProfileEntry {
  showcaseId: string;
  title: string;
  activityType: ActivityType;
  source: ActivitySource;
  startTime?: Date | undefined;
  routeThumbnailUrl: string;
  distanceMeters: number;
  durationSeconds: number;
  totalSets: number;
  totalReps: number;
  totalWeightKg: number;
  /** Reskin additions — populated on each activity sync */
  boosterCount: number;
  destinationCount: number;
  sparkline?: EntrySparkline | undefined;
  avgHeartRate?: number | undefined;
  caloriesKcal?:
    | number
    | undefined;
  /** PR tag displayed on profile activity cards (e.g. "★ DEADLIFT 180KG · +5KG") */
  prLabel?:
    | string
    | undefined;
  /**
   * HR zone minutes per bucket (index 0–4), used to aggregate LifetimeZoneSplit on the profile.
   * Populated at entry creation time from the HR zones enrichment; absent means no zone data.
   */
  hrZoneMinutes: number[];
  /** Photo URLs for activities with attached images; populated from ShowcasedActivity.photo_urls. */
  photoUrls: string[];
  createdAt?:
    | Date
    | undefined;
  /**
   * Enrichment summaries projected at entry creation time (from the hydrated
   * ActivityEnrichments) so roundups can aggregate them without re-reading GCS.
   * All optional; absent means the source enrichment did not run for this activity.
   */
  elevationGainM?:
    | number
    | undefined;
  /** e.g. "Bushy Park, London" */
  locationName?: string | undefined;
  country?: string | undefined;
  tempC?:
    | number
    | undefined;
  /** "Clear", "Rain", etc. */
  weatherDescription?:
    | string
    | undefined;
  /** reuse enrichments.BestEffort */
  bestEfforts: BestEffort[];
  /** primary muscles worked (strength) */
  primaryMuscles: string[];
}

/** EntrySparkline is a downsampled timeseries for card-level sparklines. */
export interface EntrySparkline {
  /** "heart_rate" | "pace" | "power" | "weight" */
  metric: string;
  /** ≤ 24 sample points, downsampled */
  values: number[];
}

export interface ShowcaseTheme {
  themeId: string;
  customAccentColor: string;
  animationId: string;
  cardStyle: string;
}

export interface ShowcaseLink {
  label: string;
  url: string;
}

export interface ShowcaseBioCallout {
  text: string;
}

export interface ShowcaseProfile {
  slug: string;
  userId: string;
  displayName: string;
  entries: ShowcaseProfileEntry[];
  totalActivities: number;
  totalDistanceMeters: number;
  totalDurationSeconds: number;
  latestActivityAt?: Date | undefined;
  totalSets: number;
  totalReps: number;
  totalWeightKg: number;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  subtitle: string;
  bio: string;
  profilePictureUrl: string;
  visible: boolean;
  theme?:
    | ShowcaseTheme
    | undefined;
  /** Auto-add Showcase destination when creating new pipelines */
  defaultDestination: boolean;
  showPhotoGallery: boolean;
  links: ShowcaseLink[];
  callouts: ShowcaseBioCallout[];
  /** Lifetime aggregates — written by a daily rollup job. Optional; absent means not yet computed. */
  zoneSplit?: LifetimeZoneSplit | undefined;
  streakHistory?:
    | WeeklyStreakHistory
    | undefined;
  /** Top strength PRs — populated at request time from users/{userId}/personal_records/ */
  topPrs: ShowcaseTopPR[];
  roundupSettings?: RoundupSettings | undefined;
}

/**
 * RoundupSettings controls auto-generation of showcase roundup pages.
 * Athlete-tier only; all fields default to false.
 */
export interface RoundupSettings {
  enabledWeekly: boolean;
  enabledMonthly: boolean;
  enabledYearly: boolean;
}

/** ShowcaseTopPR is a lightweight personal record for display on the profile medal wall. */
export interface ShowcaseTopPR {
  /** e.g. "bench_press_1rm" */
  recordType: string;
  /** e.g. 180 */
  value: number;
  /** "kg", "seconds", "meters" */
  unit: string;
  achievedAt?:
    | Date
    | undefined;
  /** for computing improvement delta */
  previousValue?: number | undefined;
}

export interface LifetimeZoneSplit {
  /** re-uses HeartRateZoneBucket from enrichments.proto */
  zones: HeartRateZoneBucket[];
  computedAt?:
    | Date
    | undefined;
  /** "Polarized", "Pyramidal", "Threshold" */
  label: string;
}

export interface WeeklyStreakHistory {
  /** e.g. 26 */
  weeksTracked: number;
  /** count of weeks with zero qualifying activities */
  missedWeeks: number;
  /** most-recent-last; true = had at least one activity */
  weeklyActive: boolean[];
}

/** ShowcaseDailyViewCount is one day's view/visitor counts for a sparkline/trend. */
export interface ShowcaseDailyViewCount {
  /** YYYY-MM-DD (UTC) */
  day: string;
  views: number;
  visitors: number;
}

/**
 * ShowcaseViewStats holds de-duplicated view metrics for one public showcase
 * surface. `views` is total pageviews (bot-filtered, owner's own visits excluded);
 * `visitors` is unique visitors deduped per (visitor, day) via a daily-salted hash.
 */
export interface ShowcaseViewStats {
  /** "activity:{showcaseId}" | "profile:{slug}" | "roundup:{slug}:{periodKey}" */
  targetKey: string;
  views: number;
  visitors: number;
  lastViewedAt?:
    | Date
    | undefined;
  /** recent daily timeseries (most-recent-last) */
  daily: ShowcaseDailyViewCount[];
}
