// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/activity/uploaded.proto

/* eslint-disable */
import type { DestinationType } from "../plugin/provider";
import type { ActivityEnrichments, HeartRateZoneBucket } from "./enrichments";
import type { ActivitySource, ActivityType } from "./source";
import type { StandardizedActivity } from "./standardized";

export const protobufPackage = "fitglue.models.activity";

export interface UploadedActivityRecord {
  id: string;
  userId: string;
  source: ActivitySource;
  externalId: string;
  startTime?: Date | undefined;
  destination: DestinationType;
  destinationId: string;
  uploadedAt?: Date | undefined;
}

/** ShowcasedActivity represents a publicly shareable activity snapshot. */
export interface ShowcasedActivity {
  showcaseId: string;
  activityId: string;
  userId: string;
  title: string;
  description: string;
  activityType: ActivityType;
  source: ActivitySource;
  startTime?: Date | undefined;
  activityData?: StandardizedActivity | undefined;
  fitFileUri: string;
  appliedEnrichments: string[];
  tags: string[];
  pipelineExecutionId?: string | undefined;
  createdAt?: Date | undefined;
  expiresAt?: Date | undefined;
  ownerDisplayName: string;
  activityDataUri: string;
  ownerProfilePictureUrl: string;
  ownerProfileSlug: string;
  photoUrls: string[];
  enrichments?: ActivityEnrichments | undefined;
}

export interface ShowcaseProfileEntry {
  showcaseId: string;
  title: string;
  activityType: ActivityType;
  source: ActivitySource;
  startTime?: Date | undefined;
  routeThumbnailUrl: string;
  distanceMeters: number;
  durationSeconds: number;
  totalSets: number;
  totalReps: number;
  totalWeightKg: number;
  /** Reskin additions — populated on each activity sync */
  boosterCount: number;
  destinationCount: number;
  sparkline?: EntrySparkline | undefined;
  avgHeartRate?: number | undefined;
  caloriesKcal?:
    | number
    | undefined;
  /** PR tag displayed on profile activity cards (e.g. "★ DEADLIFT 180KG · +5KG") */
  prLabel?:
    | string
    | undefined;
  /**
   * HR zone minutes per bucket (index 0–4), used to aggregate LifetimeZoneSplit on the profile.
   * Populated at entry creation time from the HR zones enrichment; absent means no zone data.
   */
  hrZoneMinutes: number[];
  /** Photo URLs for activities with attached images; populated from ShowcasedActivity.photo_urls. */
  photoUrls: string[];
  createdAt?: Date | undefined;
}

/** EntrySparkline is a downsampled timeseries for card-level sparklines. */
export interface EntrySparkline {
  /** "heart_rate" | "pace" | "power" | "weight" */
  metric: string;
  /** ≤ 24 sample points, downsampled */
  values: number[];
}

export interface ShowcaseTheme {
  themeId: string;
  customAccentColor: string;
  animationId: string;
  cardStyle: string;
}

export interface ShowcaseLink {
  label: string;
  url: string;
}

export interface ShowcaseBioCallout {
  text: string;
}

export interface ShowcaseProfile {
  slug: string;
  userId: string;
  displayName: string;
  entries: ShowcaseProfileEntry[];
  totalActivities: number;
  totalDistanceMeters: number;
  totalDurationSeconds: number;
  latestActivityAt?: Date | undefined;
  totalSets: number;
  totalReps: number;
  totalWeightKg: number;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  subtitle: string;
  bio: string;
  profilePictureUrl: string;
  visible: boolean;
  theme?:
    | ShowcaseTheme
    | undefined;
  /** Auto-add Showcase destination when creating new pipelines */
  defaultDestination: boolean;
  showPhotoGallery: boolean;
  links: ShowcaseLink[];
  callouts: ShowcaseBioCallout[];
  /** Lifetime aggregates — written by a daily rollup job. Optional; absent means not yet computed. */
  zoneSplit?: LifetimeZoneSplit | undefined;
  streakHistory?:
    | WeeklyStreakHistory
    | undefined;
  /** Top strength PRs — populated at request time from users/{userId}/personal_records/ */
  topPrs: ShowcaseTopPR[];
}

/** ShowcaseTopPR is a lightweight personal record for display on the profile medal wall. */
export interface ShowcaseTopPR {
  /** e.g. "bench_press_1rm" */
  recordType: string;
  /** e.g. 180 */
  value: number;
  /** "kg", "seconds", "meters" */
  unit: string;
  achievedAt?:
    | Date
    | undefined;
  /** for computing improvement delta */
  previousValue?: number | undefined;
}

export interface LifetimeZoneSplit {
  /** re-uses HeartRateZoneBucket from enrichments.proto */
  zones: HeartRateZoneBucket[];
  computedAt?:
    | Date
    | undefined;
  /** "Polarized", "Pyramidal", "Threshold" */
  label: string;
}

export interface WeeklyStreakHistory {
  /** e.g. 26 */
  weeksTracked: number;
  /** count of weeks with zero qualifying activities */
  missedWeeks: number;
  /** most-recent-last; true = had at least one activity */
  weeklyActive: boolean[];
}
