// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/activity/uploaded.proto

/* eslint-disable */
import type { DestinationType } from "../plugin/provider";
import type { ActivitySource, ActivityType } from "./source";
import type { StandardizedActivity } from "./standardized";

export const protobufPackage = "fitglue.models.activity";

export interface UploadedActivityRecord {
  id: string;
  userId: string;
  source: ActivitySource;
  externalId: string;
  startTime?: Date | undefined;
  destination: DestinationType;
  destinationId: string;
  uploadedAt?: Date | undefined;
}

/** ShowcasedActivity represents a publicly shareable activity snapshot. */
export interface ShowcasedActivity {
  showcaseId: string;
  activityId: string;
  userId: string;
  title: string;
  description: string;
  activityType: ActivityType;
  source: ActivitySource;
  startTime?: Date | undefined;
  activityData?: StandardizedActivity | undefined;
  fitFileUri: string;
  appliedEnrichments: string[];
  enrichmentMetadata: { [key: string]: string };
  tags: string[];
  pipelineExecutionId?: string | undefined;
  createdAt?: Date | undefined;
  expiresAt?: Date | undefined;
  ownerDisplayName: string;
  activityDataUri: string;
}

export interface ShowcasedActivity_EnrichmentMetadataEntry {
  key: string;
  value: string;
}

export interface ShowcaseProfileEntry {
  showcaseId: string;
  title: string;
  activityType: ActivityType;
  source: ActivitySource;
  startTime?: Date | undefined;
  routeThumbnailUrl: string;
  distanceMeters: number;
  durationSeconds: number;
  totalSets: number;
  totalReps: number;
  totalWeightKg: number;
}

export interface ShowcaseTheme {
  themeId: string;
  customAccentColor: string;
  animationId: string;
  cardStyle: string;
}

export interface ShowcaseProfile {
  slug: string;
  userId: string;
  displayName: string;
  entries: ShowcaseProfileEntry[];
  totalActivities: number;
  totalDistanceMeters: number;
  totalDurationSeconds: number;
  latestActivityAt?: Date | undefined;
  totalSets: number;
  totalReps: number;
  totalWeightKg: number;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  subtitle: string;
  bio: string;
  profilePictureUrl: string;
  visible: boolean;
  theme?: ShowcaseTheme | undefined;
}
