// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/pipeline/execution.proto

/* eslint-disable */
import type { ActivityType } from "../activity/source";
import type { DestinationType } from "../plugin/provider";

export const protobufPackage = "fitglue.models.pipeline";

export enum PipelineRunStatus {
  PIPELINE_RUN_STATUS_UNSPECIFIED = 0,
  PIPELINE_RUN_STATUS_RUNNING = 1,
  PIPELINE_RUN_STATUS_SYNCED = 2,
  PIPELINE_RUN_STATUS_PARTIAL = 3,
  PIPELINE_RUN_STATUS_FAILED = 4,
  PIPELINE_RUN_STATUS_PENDING = 5,
  PIPELINE_RUN_STATUS_SKIPPED = 6,
  PIPELINE_RUN_STATUS_ARCHIVED = 7,
  PIPELINE_RUN_STATUS_TIER_BLOCKED = 8,
  UNRECOGNIZED = -1,
}

export enum DestinationStatus {
  DESTINATION_STATUS_UNSPECIFIED = 0,
  DESTINATION_STATUS_PENDING = 1,
  DESTINATION_STATUS_SUCCESS = 2,
  DESTINATION_STATUS_FAILED = 3,
  DESTINATION_STATUS_SKIPPED = 4,
  UNRECOGNIZED = -1,
}

export enum ExecutionStatus {
  STATUS_UNSPECIFIED = 0,
  STATUS_STARTED = 1,
  STATUS_SUCCESS = 2,
  STATUS_FAILED = 3,
  STATUS_PENDING = 4,
  STATUS_WAITING = 5,
  STATUS_LAGGED_RETRY = 6,
  STATUS_SKIPPED = 7,
  UNRECOGNIZED = -1,
}

export interface PipelineRun {
  id: string;
  pipelineId: string;
  activityId: string;
  source: string;
  sourceActivityId: string;
  title: string;
  description: string;
  type: ActivityType;
  startTime?: Date | undefined;
  status: PipelineRunStatus;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  boosters: BoosterExecution[];
  destinations: DestinationOutcome[];
  statusMessage?: string | undefined;
  pendingInputId?: string | undefined;
  originalPayloadUri: string;
  enrichedEventUri: string;
}

export interface BoosterExecution {
  providerName: string;
  status: string;
  durationMs: number;
  metadata: { [key: string]: string };
  error?: string | undefined;
}

export interface BoosterExecution_MetadataEntry {
  key: string;
  value: string;
}

export interface DestinationOutcome {
  destination: DestinationType;
  status: DestinationStatus;
  externalId?: string | undefined;
  error?: string | undefined;
  completedAt?: Date | undefined;
}

export interface ExecutionRecord {
  executionId: string;
  service: string;
  status: ExecutionStatus;
  timestamp?: Date | undefined;
  triggerType: string;
  userId?: string | undefined;
  testRunId?: string | undefined;
  startTime?: Date | undefined;
  endTime?: Date | undefined;
  errorMessage?: string | undefined;
  inputsJson?: string | undefined;
  outputsJson?: string | undefined;
  expireAt?: Date | undefined;
  pipelineExecutionId?: string | undefined;
}
