// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/pipeline/pending_input.proto

/* eslint-disable */

export const protobufPackage = "fitglue.models.pipeline";

export enum ParkrunResultsState {
  PARKRUN_RESULTS_STATE_UNSPECIFIED = 0,
  PARKRUN_RESULTS_STATE_PENDING = 1,
  PARKRUN_RESULTS_STATE_COMPLETE = 2,
  PARKRUN_RESULTS_STATE_EXPIRED = 3,
  PARKRUN_RESULTS_STATE_IMMEDIATE = 4,
  UNRECOGNIZED = -1,
}

export interface PendingInput {
  activityId: string;
  userId: string;
  status: PendingInput_Status;
  requiredFields: string[];
  inputData: { [key: string]: string };
  originalPayloadUri: string;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  completedAt?: Date | undefined;
  continuedWithoutResolution: boolean;
  linkedActivityId: string;
  pipelineId: string;
  enricherProviderId: string;
  autoPopulated: boolean;
  autoDeadline?: Date | undefined;
  providerMetadata: { [key: string]: string };
}

export enum PendingInput_Status {
  STATUS_UNSPECIFIED = 0,
  STATUS_WAITING = 1,
  STATUS_COMPLETED = 2,
  UNRECOGNIZED = -1,
}

export interface PendingInput_InputDataEntry {
  key: string;
  value: string;
}

export interface PendingInput_ProviderMetadataEntry {
  key: string;
  value: string;
}
