// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/plugin/manifest.proto

/* eslint-disable */

export const protobufPackage = "fitglue.models.plugin";

export enum PluginType {
  PLUGIN_TYPE_UNSPECIFIED = 0,
  PLUGIN_TYPE_SOURCE = 1,
  PLUGIN_TYPE_ENRICHER = 2,
  PLUGIN_TYPE_DESTINATION = 3,
  UNRECOGNIZED = -1,
}

export enum ConfigFieldType {
  CONFIG_FIELD_TYPE_UNSPECIFIED = 0,
  CONFIG_FIELD_TYPE_STRING = 1,
  CONFIG_FIELD_TYPE_NUMBER = 2,
  CONFIG_FIELD_TYPE_BOOLEAN = 3,
  CONFIG_FIELD_TYPE_SELECT = 4,
  CONFIG_FIELD_TYPE_MULTI_SELECT = 5,
  CONFIG_FIELD_TYPE_KEY_VALUE_MAP = 6,
  CONFIG_FIELD_TYPE_DYNAMIC_SELECT = 7,
  UNRECOGNIZED = -1,
}

export enum IntegrationAuthType {
  INTEGRATION_AUTH_TYPE_UNSPECIFIED = 0,
  INTEGRATION_AUTH_TYPE_OAUTH = 1,
  INTEGRATION_AUTH_TYPE_API_KEY = 2,
  INTEGRATION_AUTH_TYPE_APP_SYNC = 3,
  INTEGRATION_AUTH_TYPE_PUBLIC_ID = 4,
  UNRECOGNIZED = -1,
}

export interface PluginManifest {
  id: string;
  type: PluginType;
  name: string;
  description: string;
  icon: string;
  configSchema: ConfigFieldSchema[];
  requiredIntegrations: string[];
  enabled: boolean;
  enricherProviderType?: number | undefined;
  destinationType?: number | undefined;
  marketingDescription: string;
  features: string[];
  transformations: Transformation[];
  useCases: string[];
  externalUrlTemplate?: string | undefined;
  requiredTier?: string | undefined;
  category?: string | undefined;
  sortOrder?: number | undefined;
  isPremium?: boolean | undefined;
  popularityScore?: number | undefined;
  iconType?: string | undefined;
  iconPath?: string | undefined;
  isTemporarilyUnavailable?: boolean | undefined;
  allowMultipleInstances?: boolean | undefined;
}

export interface Transformation {
  field: string;
  label: string;
  before: string;
  after: string;
  visualType: string;
  afterHtml: string;
}

export interface ConfigFieldSchema {
  key: string;
  label: string;
  description: string;
  fieldType: ConfigFieldType;
  required: boolean;
  defaultValue: string;
  options: ConfigFieldOption[];
  validation?: ConfigFieldValidation | undefined;
  dependsOn?: ConfigFieldDependency | undefined;
  keyOptions: ConfigFieldOption[];
  valueOptions: ConfigFieldOption[];
  dynamicSource?: string | undefined;
  valueDynamicSource?: string | undefined;
}

export interface ConfigFieldDependency {
  fieldKey: string;
  values: string[];
}

export interface ConfigFieldOption {
  value: string;
  label: string;
}

export interface ConfigFieldValidation {
  minLength?: number | undefined;
  maxLength?: number | undefined;
  pattern?: string | undefined;
  minValue?: number | undefined;
  maxValue?: number | undefined;
}

export interface IntegrationAction {
  id: string;
  label: string;
  description: string;
  icon: string;
}

export interface IntegrationManifest {
  id: string;
  name: string;
  description: string;
  icon: string;
  authType: IntegrationAuthType;
  enabled: boolean;
  docsUrl: string;
  setupTitle: string;
  setupInstructions: string;
  apiKeyLabel: string;
  apiKeyHelpUrl: string;
  marketingDescription: string;
  features: string[];
  iconType?: string | undefined;
  iconPath?: string | undefined;
  isTemporarilyUnavailable?: boolean | undefined;
  actions: IntegrationAction[];
}

export interface PluginRegistryResponse {
  sources: PluginManifest[];
  enrichers: PluginManifest[];
  destinations: PluginManifest[];
  integrations: IntegrationManifest[];
}
