// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: services/pipeline/pipeline.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";
import type { PipelineConfig } from "../../models/pipeline/config";
import type { PipelineRun } from "../../models/pipeline/execution";
import type { PendingInput } from "../../models/pipeline/pending_input";

export const protobufPackage = "fitglue.services.pipeline";

export interface ListPipelinesRequest {
  userId: string;
}

export interface ListPipelinesResponse {
  pipelines: PipelineConfig[];
}

export interface GetPipelineRequest {
  userId: string;
  pipelineId: string;
}

export interface CreatePipelineRequest {
  userId: string;
  pipeline?: PipelineConfig | undefined;
}

export interface UpdatePipelineRequest {
  userId: string;
  pipelineId: string;
  pipeline?: PipelineConfig | undefined;
}

export interface DeletePipelineRequest {
  userId: string;
  pipelineId: string;
}

export interface SubmitInputRequest {
  userId: string;
  pendingInputId: string;
  inputData: { [key: string]: string };
}

export interface SubmitInputRequest_InputDataEntry {
  key: string;
  value: string;
}

export interface ListPendingInputsRequest {
  userId: string;
}

export interface ListPendingInputsResponse {
  inputs: PendingInput[];
}

export interface ResolvePendingInputRequest {
  userId: string;
  pendingInputId: string;
}

export interface RepostActivityRequest {
  userId: string;
  activityId: string;
  /** Repost mode: "missed-destination", "retry-destination", "full-pipeline" */
  mode: string;
  /** Target destination (required for missed-destination and retry-destination modes) */
  destination: string;
}

export interface GetPipelineRunRequest {
  userId: string;
  runId: string;
}

export interface ListPipelineRunsRequest {
  userId: string;
  pipelineId: string;
  limit: number;
  pageToken: string;
}

export interface ListPipelineRunsResponse {
  runs: PipelineRun[];
  nextPageToken: string;
}

export interface PipelineService {
  ListPipelines(request: ListPipelinesRequest): Promise<ListPipelinesResponse>;
  GetPipeline(request: GetPipelineRequest): Promise<PipelineConfig>;
  CreatePipeline(request: CreatePipelineRequest): Promise<PipelineConfig>;
  UpdatePipeline(request: UpdatePipelineRequest): Promise<PipelineConfig>;
  DeletePipeline(request: DeletePipelineRequest): Promise<Empty>;
  SubmitInput(request: SubmitInputRequest): Promise<Empty>;
  ListPendingInputs(request: ListPendingInputsRequest): Promise<ListPendingInputsResponse>;
  ResolvePendingInput(request: ResolvePendingInputRequest): Promise<Empty>;
  RepostActivity(request: RepostActivityRequest): Promise<Empty>;
  GetPipelineRun(request: GetPipelineRunRequest): Promise<PipelineRun>;
  ListPipelineRuns(request: ListPipelineRunsRequest): Promise<ListPipelineRunsResponse>;
}
