// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: gateway/admin.proto

/* eslint-disable */
import type { PipelineConfig } from "../models/pipeline/config";
import type { PipelineRun } from "../models/pipeline/execution";
import type { UserProfile } from "../models/user/profile";

export const protobufPackage = "fitglue.gateway";

export interface AdminEmptyResponse {
}

/** Platform Stats */
export interface GetAdminStatsRequest {
}

export interface RecentPipelineRunCounts {
  success: number;
  failed: number;
  started: number;
}

export interface GetAdminStatsResponse {
  totalUsers: number;
  athleteUsers: number;
  adminUsers: number;
  totalSyncsThisMonth: number;
  recentExecutions?: RecentPipelineRunCounts | undefined;
}

/** User Management */
export interface ListUsersAdminRequest {
  limit: number;
  pageToken: string;
}

export interface ListUsersAdminResponse {
  users: UserProfile[];
  nextPageToken: string;
}

export interface UserIdAdminRequest {
  id: string;
}

export interface UpdateUserAdminRequest {
  id: string;
  accessEnabled: boolean;
}

export interface DeleteUserDataAdminRequest {
  id: string;
  dataType: string;
}

/** Pipeline Management */
export interface ListAllPipelinesAdminRequest {
  /** required query param */
  userId: string;
}

export interface ListAllPipelinesAdminResponse {
  pipelines: PipelineConfig[];
}

export interface ListPipelineRunsAdminRequest {
  status: string;
  source: string;
  userId: string;
  limit: number;
  pageToken: string;
}

export interface ListPipelineRunsAdminResponse {
  runs: PipelineRun[];
  nextPageToken: string;
}

/**
 * AdminGatewayService describes the admin REST API surface
 * served by api-admin at /api/admin/*.
 *
 * Requires admin authentication via AdminMiddleware.
 */
export interface AdminGatewayService {
  /** ===================== Platform Stats ===================== */
  GetStats(request: GetAdminStatsRequest): Promise<GetAdminStatsResponse>;
  /** ===================== User Management ===================== */
  ListUsers(request: ListUsersAdminRequest): Promise<ListUsersAdminResponse>;
  GetUser(request: UserIdAdminRequest): Promise<UserProfile>;
  UpdateUser(request: UpdateUserAdminRequest): Promise<UserProfile>;
  DeleteUser(request: UserIdAdminRequest): Promise<AdminEmptyResponse>;
  DeleteUserData(request: DeleteUserDataAdminRequest): Promise<AdminEmptyResponse>;
  /** ===================== Pipeline Management ===================== */
  ListAllPipelines(request: ListAllPipelinesAdminRequest): Promise<ListAllPipelinesAdminResponse>;
  ListPipelineRuns(request: ListPipelineRunsAdminRequest): Promise<ListPipelineRunsAdminResponse>;
}
