// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: gateway/public.proto

/* eslint-disable */
import type { Empty } from "../google/protobuf/empty";
import type { ShowcaseRoundup } from "../models/activity/roundup";
import type { ShowcasedActivity, ShowcaseProfile } from "../models/activity/uploaded";
import type { PluginManifest, PluginRegistryResponse } from "../models/plugin/manifest";

export const protobufPackage = "fitglue.gateway";

export interface PublicEmptyRequest {
}

/** Registry */
export interface ListPluginsPublicRequest {
  /** optional query param */
  category: string;
}

export interface ListPluginsPublicResponse {
  plugins: PluginManifest[];
}

export interface GetPluginPublicRequest {
  id: string;
}

export interface ListCategoriesPublicResponse {
  categories: string[];
}

export interface ListSourcesPublicResponse {
  sources: PluginManifest[];
}

/** Showcase */
export interface GetPublicShowcaseRequest {
  id: string;
}

export interface GetPublicShowcaseProfileRequest {
  slug: string;
  /** optional query param */
  page: number;
}

export interface GetPublicShowcaseProfileResponse {
  profile?: ShowcaseProfile | undefined;
  showcases: ShowcasedActivity[];
  totalPages: number;
  currentPage: number;
}

export interface GetPublicRoundupGatewayRequest {
  slug: string;
  periodKey: string;
}

export interface GetRecentPublicRoundupsGatewayRequest {
  slug: string;
  /** optional query param — 1-indexed, defaults to 1 */
  page: number;
}

export interface GetRecentPublicRoundupsGatewayResponse {
  roundups: ShowcaseRoundup[];
  totalPages: number;
  currentPage: number;
}

/** Showcase view beacons (visitor identity is derived server-side from IP/UA) */
export interface RecordShowcaseActivityViewRequest {
  id: string;
}

export interface RecordShowcaseProfileViewRequest {
  slug: string;
}

export interface RecordShowcaseRoundupViewRequest {
  slug: string;
  periodKey: string;
}

/**
 * PublicGatewayService describes the unauthenticated REST API surface
 * served by api-public at /api/public/*.
 *
 * No authentication required. Used by marketing pages, Skier builds,
 * and public showcase profile pages.
 */
export interface PublicGatewayService {
  /** ===================== Registry ===================== */
  GetPluginRegistry(request: PublicEmptyRequest): Promise<PluginRegistryResponse>;
  ListPlugins(request: ListPluginsPublicRequest): Promise<ListPluginsPublicResponse>;
  GetPlugin(request: GetPluginPublicRequest): Promise<PluginManifest>;
  ListCategories(request: PublicEmptyRequest): Promise<ListCategoriesPublicResponse>;
  ListSources(request: PublicEmptyRequest): Promise<ListSourcesPublicResponse>;
  /** ===================== Public Showcase ===================== */
  GetPublicShowcase(request: GetPublicShowcaseRequest): Promise<ShowcasedActivity>;
  GetPublicShowcaseProfile(request: GetPublicShowcaseProfileRequest): Promise<GetPublicShowcaseProfileResponse>;
  GetPublicRoundup(request: GetPublicRoundupGatewayRequest): Promise<ShowcaseRoundup>;
  GetRecentPublicRoundups(
    request: GetRecentPublicRoundupsGatewayRequest,
  ): Promise<GetRecentPublicRoundupsGatewayResponse>;
  /**
   * ===================== Showcase View Beacons =====================
   * Fire-and-forget view beacons fired by the public showcase SPA on page load.
   * Always respond 204; counts are never returned here.
   */
  RecordShowcaseActivityView(request: RecordShowcaseActivityViewRequest): Promise<Empty>;
  RecordShowcaseProfileView(request: RecordShowcaseProfileViewRequest): Promise<Empty>;
  RecordShowcaseRoundupView(request: RecordShowcaseRoundupViewRequest): Promise<Empty>;
}
