// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v3.12.4
// source: pending_input.proto

/* eslint-disable */
import type { ActivityPayload } from "./activity";

export const protobufPackage = "fitglue";

/**
 * PendingInput represents a paused pipeline execution waiting for user interaction.
 * For auto-populated inputs (e.g., Parkrun results), the pipeline continues and resumes later.
 */
export interface PendingInput {
  activityId: string;
  userId: string;
  status: PendingInput_Status;
  /** Fields the user interface should ask for (e.g. "title", "description") */
  requiredFields: string[];
  /** Data provided by the user or auto-populated (filled when status=COMPLETED) */
  inputData: { [key: string]: string };
  /** The original payload to be re-published once input is provided */
  originalPayload?: ActivityPayload | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  completedAt?:
    | Date
    | undefined;
  /** For "continue anyway" enrichers (e.g., Parkrun) - pipeline continues despite pending input */
  continuedWithoutResolution: boolean;
  /** Activity that was created while pending */
  linkedActivityId: string;
  /** Pipeline that contains this enricher */
  pipelineId: string;
  /** Enricher that created this pending input */
  enricherProviderId: string;
  /** Auto-population mode - system will auto-fill, not user */
  autoPopulated: boolean;
  /** If not auto-resolved by deadline, prompt user */
  autoDeadline?: Date | undefined;
}

export enum PendingInput_Status {
  STATUS_UNSPECIFIED = 0,
  STATUS_WAITING = 1,
  STATUS_COMPLETED = 2,
  UNRECOGNIZED = -1,
}

export interface PendingInput_InputDataEntry {
  key: string;
  value: string;
}
