// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v3.12.4
// source: plugin.proto

/* eslint-disable */

export const protobufPackage = "fitglue";

/** PluginType categorizes plugins */
export enum PluginType {
  PLUGIN_TYPE_UNSPECIFIED = 0,
  PLUGIN_TYPE_SOURCE = 1,
  PLUGIN_TYPE_ENRICHER = 2,
  PLUGIN_TYPE_DESTINATION = 3,
  UNRECOGNIZED = -1,
}

export enum ConfigFieldType {
  CONFIG_FIELD_TYPE_UNSPECIFIED = 0,
  CONFIG_FIELD_TYPE_STRING = 1,
  CONFIG_FIELD_TYPE_NUMBER = 2,
  CONFIG_FIELD_TYPE_BOOLEAN = 3,
  /** CONFIG_FIELD_TYPE_SELECT - Dropdown */
  CONFIG_FIELD_TYPE_SELECT = 4,
  /** CONFIG_FIELD_TYPE_MULTI_SELECT - Multiple selection */
  CONFIG_FIELD_TYPE_MULTI_SELECT = 5,
  /** CONFIG_FIELD_TYPE_KEY_VALUE_MAP - Record<string, string> map - stored as JSON */
  CONFIG_FIELD_TYPE_KEY_VALUE_MAP = 6,
  /** CONFIG_FIELD_TYPE_DYNAMIC_SELECT - Dropdown with options fetched from API + allows new entry */
  CONFIG_FIELD_TYPE_DYNAMIC_SELECT = 7,
  UNRECOGNIZED = -1,
}

/** IntegrationAuthType defines how users authenticate with an integration */
export enum IntegrationAuthType {
  INTEGRATION_AUTH_TYPE_UNSPECIFIED = 0,
  INTEGRATION_AUTH_TYPE_OAUTH = 1,
  INTEGRATION_AUTH_TYPE_API_KEY = 2,
  /** INTEGRATION_AUTH_TYPE_APP_SYNC - Mobile app handles auth (Apple Health, Health Connect) */
  INTEGRATION_AUTH_TYPE_APP_SYNC = 3,
  /** INTEGRATION_AUTH_TYPE_PUBLIC_ID - Public identifier (no secrets, no ingress key needed) */
  INTEGRATION_AUTH_TYPE_PUBLIC_ID = 4,
  UNRECOGNIZED = -1,
}

/** PluginManifest defines metadata for any plugin */
export interface PluginManifest {
  /** Unique identifier (e.g., "hevy", "fitbit-hr", "strava") */
  id: string;
  /** Source, Enricher, or Destination */
  type: PluginType;
  /** Human-readable name */
  name: string;
  /** Short description */
  description: string;
  /** Emoji or icon name */
  icon: string;
  /** Configuration fields */
  configSchema: ConfigFieldSchema[];
  /** e.g., ["fitbit"] requires Fitbit connected */
  requiredIntegrations: string[];
  /** Whether this plugin is available */
  enabled: boolean;
  /** For enrichers: links to the EnricherProviderType enum value */
  enricherProviderType?:
    | number
    | undefined;
  /** For destinations: links to the Destination enum value */
  destinationType?:
    | number
    | undefined;
  /** Marketing metadata */
  marketingDescription: string;
  /** List of features/capabilities to display */
  features: string[];
  /** Before/after examples showing what the plugin does */
  transformations: Transformation[];
  /** List of use cases (e.g., "Share detailed workout logs") */
  useCases: string[];
  /**
   * URL template for linking to external activities. Use {id} placeholder.
   * For internal destinations like Showcase, server injects env-specific base URL.
   */
  externalUrlTemplate?:
    | string
    | undefined;
  /** Required tier to use this plugin (e.g., "pro" for Athlete-only features) */
  requiredTier?:
    | string
    | undefined;
  /** UX Organization fields */
  category?:
    | string
    | undefined;
  /** Ordering within category (lower = first) */
  sortOrder?:
    | number
    | undefined;
  /** Display premium badge (Athlete-tier) */
  isPremium?:
    | boolean
    | undefined;
  /** For "recommended" sorting in wizard */
  popularityScore?:
    | number
    | undefined;
  /** SVG Icon support (for products with real logos) */
  iconType?:
    | string
    | undefined;
  /** Path to SVG asset (e.g., "/assets/icons/strava.svg") */
  iconPath?:
    | string
    | undefined;
  /** When true, plugin is hidden from app but still shown on marketing site with "Coming Soon" indicator */
  isTemporarilyUnavailable?: boolean | undefined;
}

/** Transformation shows a before/after example of what a plugin does to a field */
export interface Transformation {
  /** Field being transformed (e.g., "description", "gpsData") */
  field: string;
  /** Human-readable label (e.g., "Activity Description") */
  label: string;
  /** Example value before transformation */
  before: string;
  /** Example value after transformation */
  after: string;
  /** Visual rendering type (e.g., "hr-graph", "gps-map") - if set, renders SVG instead of text */
  visualType: string;
  /** Pre-formatted HTML for after state (used instead of after when set) */
  afterHtml: string;
}

/** ConfigFieldSchema defines a single configuration field */
export interface ConfigFieldSchema {
  /** Field key in config map */
  key: string;
  /** Human-readable label */
  label: string;
  /** Help text */
  description: string;
  /** Type of input */
  fieldType: ConfigFieldType;
  /** Whether field is required */
  required: boolean;
  /** Default value (as string) */
  defaultValue: string;
  /** For SELECT/MULTI_SELECT types */
  options: ConfigFieldOption[];
  /** Validation rules */
  validation?:
    | ConfigFieldValidation
    | undefined;
  /** Show only when dependency is met */
  dependsOn?:
    | ConfigFieldDependency
    | undefined;
  /**
   * For KEY_VALUE_MAP: independent options for left (key) and right (value) sides
   * If set, renders a dropdown instead of text input for that side
   */
  keyOptions: ConfigFieldOption[];
  /** Options for the right side (value) */
  valueOptions: ConfigFieldOption[];
  /** For DYNAMIC_SELECT: identifier for which endpoint to fetch options from */
  dynamicSource?: string | undefined;
}

/** ConfigFieldDependency defines when a field should be visible */
export interface ConfigFieldDependency {
  /** Key of the field this depends on */
  fieldKey: string;
  /** Show when dependent field has one of these values */
  values: string[];
}

export interface ConfigFieldOption {
  /** Stored value (descriptive string) */
  value: string;
  /** Display label */
  label: string;
}

export interface ConfigFieldValidation {
  minLength?: number | undefined;
  maxLength?:
    | number
    | undefined;
  /** Regex pattern */
  pattern?: string | undefined;
  minValue?: number | undefined;
  maxValue?: number | undefined;
}

/** IntegrationManifest defines metadata for external service integrations */
export interface IntegrationManifest {
  /** Unique identifier (e.g., "hevy", "fitbit", "strava") */
  id: string;
  /** Human-readable name */
  name: string;
  /** Short description */
  description: string;
  /** Emoji or icon name */
  icon: string;
  /** How users connect */
  authType: IntegrationAuthType;
  /** Whether this integration is available */
  enabled: boolean;
  /** Link to setup guide */
  docsUrl: string;
  /** Setup configuration */
  setupTitle: string;
  /** Markdown-formatted setup steps */
  setupInstructions: string;
  /** Label for API key input e.g., "API Key" */
  apiKeyLabel: string;
  /** URL where user gets the key */
  apiKeyHelpUrl: string;
  /** Marketing metadata */
  marketingDescription: string;
  /** List of features/capabilities */
  features: string[];
  /** When true, integration is hidden from connections page but shown on marketing with "Coming Soon" */
  isTemporarilyUnavailable?: boolean | undefined;
}

/** PluginRegistryResponse for API discovery */
export interface PluginRegistryResponse {
  sources: PluginManifest[];
  enrichers: PluginManifest[];
  destinations: PluginManifest[];
  integrations: IntegrationManifest[];
}
