// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: uploaded_activity.proto

/* eslint-disable */
import type { ActivitySource } from "./activity";
import type { Destination } from "./events";

export const protobufPackage = "fitglue";

/**
 * UploadedActivityRecord tracks activities we've uploaded to destinations.
 * Used for loop prevention: when a webhook comes back, we check if we just uploaded it.
 */
export interface UploadedActivityRecord {
  /** Composite ID: "{source}:{external_id}" for efficient lookup */
  id: string;
  userId: string;
  /** Activity identification */
  source: ActivitySource;
  /** External ID on the source platform */
  externalId: string;
  /** Activity start time for deduplication */
  startTime?:
    | Date
    | undefined;
  /** Destination info */
  destination: Destination;
  /** ID on the destination platform */
  destinationId: string;
  /** Timestamp for TTL-based cleanup */
  uploadedAt?: Date | undefined;
}
