// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.4
// source: user.proto

/* eslint-disable */
import type { ActivitySource } from "./activity";
import type { Destination } from "./events";
import type { ActivityType, StandardizedActivity } from "./standardized_activity";

export const protobufPackage = "fitglue";

export enum UserTier {
  USER_TIER_UNSPECIFIED = 0,
  USER_TIER_HOBBYIST = 1,
  USER_TIER_ATHLETE = 2,
  UNRECOGNIZED = -1,
}

export enum EnricherProviderType {
  ENRICHER_PROVIDER_UNSPECIFIED = 0,
  ENRICHER_PROVIDER_FITBIT_HEART_RATE = 1,
  /** ENRICHER_PROVIDER_WORKOUT_SUMMARY - Config inputs: "format" (compact/detailed/verbose), "show_stats" ("true"/"false") */
  ENRICHER_PROVIDER_WORKOUT_SUMMARY = 2,
  ENRICHER_PROVIDER_MUSCLE_HEATMAP = 3,
  ENRICHER_PROVIDER_SOURCE_LINK = 4,
  /** ENRICHER_PROVIDER_VIRTUAL_GPS - 5 was METADATA_PASSTHROUGH (removed) */
  ENRICHER_PROVIDER_VIRTUAL_GPS = 6,
  ENRICHER_PROVIDER_TYPE_MAPPER = 7,
  ENRICHER_PROVIDER_PARKRUN = 8,
  ENRICHER_PROVIDER_CONDITION_MATCHER = 9,
  ENRICHER_PROVIDER_AUTO_INCREMENT = 10,
  ENRICHER_PROVIDER_USER_INPUT = 11,
  /** ENRICHER_PROVIDER_ACTIVITY_FILTER - Config inputs: "exclude_activity_types" (comma-separated), "exclude_title_contains" (string) */
  ENRICHER_PROVIDER_ACTIVITY_FILTER = 12,
  /** ENRICHER_PROVIDER_LOGIC_GATE - Config inputs: "logic_config" (JSON string with rules, match_mode, on_match, on_no_match) */
  ENRICHER_PROVIDER_LOGIC_GATE = 13,
  /** ENRICHER_PROVIDER_HEART_RATE_SUMMARY - Config inputs: none (calculates min/avg/max HR from existing heartrate data) */
  ENRICHER_PROVIDER_HEART_RATE_SUMMARY = 14,
  /** ENRICHER_PROVIDER_AI_COMPANION - Config inputs: "mode" (title/description/both) - Athlete tier only */
  ENRICHER_PROVIDER_AI_COMPANION = 15,
  /** ENRICHER_PROVIDER_PACE_SUMMARY - Config inputs: none (calculates from speed data, formats as min/km for running) */
  ENRICHER_PROVIDER_PACE_SUMMARY = 16,
  /** ENRICHER_PROVIDER_CADENCE_SUMMARY - Config inputs: none (calculates avg/max cadence from cadence data) */
  ENRICHER_PROVIDER_CADENCE_SUMMARY = 17,
  /** ENRICHER_PROVIDER_POWER_SUMMARY - Config inputs: none (calculates avg/max power from power data) */
  ENRICHER_PROVIDER_POWER_SUMMARY = 18,
  /** ENRICHER_PROVIDER_SPEED_SUMMARY - Config inputs: none (calculates avg/max speed from speed data) */
  ENRICHER_PROVIDER_SPEED_SUMMARY = 19,
  /** ENRICHER_PROVIDER_PERSONAL_RECORDS - Config inputs: "cardio_records" (boolean), "strength_records" (boolean), "celebrate_in_title" (boolean) */
  ENRICHER_PROVIDER_PERSONAL_RECORDS = 20,
  ENRICHER_PROVIDER_TRAINING_LOAD = 21,
  /** ENRICHER_PROVIDER_SPOTIFY_TRACKS - Config inputs: none (fetches Spotify tracks played during activity time window) */
  ENRICHER_PROVIDER_SPOTIFY_TRACKS = 22,
  /** ENRICHER_PROVIDER_WEATHER - Config inputs: "include_wind" (boolean, default true) - adds weather conditions to outdoor activities */
  ENRICHER_PROVIDER_WEATHER = 23,
  /** ENRICHER_PROVIDER_ELEVATION_SUMMARY - Config inputs: none (calculates elevation gain/loss/max from altitude data) */
  ENRICHER_PROVIDER_ELEVATION_SUMMARY = 24,
  /** ENRICHER_PROVIDER_LOCATION_NAMING - Config inputs: "mode" (title/description), "title_template", "fallback_enabled" - generates location-based titles from GPS */
  ENRICHER_PROVIDER_LOCATION_NAMING = 25,
  /** ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE - Config inputs: none (generates SVG muscle activation image) - Athlete tier only */
  ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE = 26,
  /** ENRICHER_PROVIDER_ROUTE_THUMBNAIL - Config inputs: "width", "height", "style", "line_color", "line_width" - generates static map image of GPS route - Athlete tier only */
  ENRICHER_PROVIDER_ROUTE_THUMBNAIL = 27,
  /** ENRICHER_PROVIDER_AI_BANNER - Config inputs: "style" (vibrant/minimal/dramatic), "subject" (male/female/abstract) - generates AI banner image for Showcase - Athlete tier only */
  ENRICHER_PROVIDER_AI_BANNER = 28,
  /** ENRICHER_PROVIDER_FIT_FILE_HEART_RATE - Config inputs: none (requests FIT file upload via pending input, extracts HR data for merging) */
  ENRICHER_PROVIDER_FIT_FILE_HEART_RATE = 29,
  /** ENRICHER_PROVIDER_HYBRID_RACE_TAGGER - Config inputs: none (allows tagging and merging laps for hybrid races like Hyrox, ATHX) */
  ENRICHER_PROVIDER_HYBRID_RACE_TAGGER = 30,
  /** ENRICHER_PROVIDER_RUNNING_DYNAMICS - Config inputs: none (summarizes ground contact time, vertical oscillation, etc.) - Athlete tier only */
  ENRICHER_PROVIDER_RUNNING_DYNAMICS = 31,
  /** ENRICHER_PROVIDER_HEART_RATE_ZONES - Config inputs: "max_hr" (optional, default 190), "style" (emoji/percentage/text), "bar_length" (3-10) - shows time in each heart rate zone */
  ENRICHER_PROVIDER_HEART_RATE_ZONES = 32,
  /** ENRICHER_PROVIDER_CALORIES_BURNED - Config inputs: "fun_mode" (boolean, shows food equivalents), "user_weight" (optional, kg) - estimates calories burned */
  ENRICHER_PROVIDER_CALORIES_BURNED = 33,
  /** ENRICHER_PROVIDER_GOAL_TRACKER - Config inputs: "period" (week/month/year), "metric" (distance/duration/activities/elevation), "target" - tracks goal progress */
  ENRICHER_PROVIDER_GOAL_TRACKER = 34,
  /** ENRICHER_PROVIDER_STREAK_TRACKER - Config inputs: "activity_types" (any/running/cycling/etc) - tracks consecutive activity streaks */
  ENRICHER_PROVIDER_STREAK_TRACKER = 35,
  /** ENRICHER_PROVIDER_DISTANCE_MILESTONES - Config inputs: "sport" (any/running/cycling/etc) - celebrates lifetime distance milestones */
  ENRICHER_PROVIDER_DISTANCE_MILESTONES = 36,
  /** ENRICHER_PROVIDER_RECOVERY_ADVISOR - Config inputs: none (calculates training load and suggests recovery) - Athlete tier only */
  ENRICHER_PROVIDER_RECOVERY_ADVISOR = 37,
  /** ENRICHER_PROVIDER_EFFORT_SCORE - Config inputs: none (computes relative effort score 0-100 against rolling 14-day history) */
  ENRICHER_PROVIDER_EFFORT_SCORE = 38,
  /** ENRICHER_PROVIDER_INTERVALS - Config inputs: "show_all_intervals" (boolean), "show_progression" (boolean), "show_summary" (boolean) */
  ENRICHER_PROVIDER_INTERVALS = 39,
  ENRICHER_PROVIDER_MOCK = 99,
  UNRECOGNIZED = -1,
}

/** Workout Summary format styles */
export enum WorkoutSummaryFormat {
  WORKOUT_SUMMARY_FORMAT_UNSPECIFIED = 0,
  /** WORKOUT_SUMMARY_FORMAT_COMPACT - "4×8@100kg" */
  WORKOUT_SUMMARY_FORMAT_COMPACT = 1,
  /** WORKOUT_SUMMARY_FORMAT_DETAILED - "4 sets × 8 reps @ 100.0kg" */
  WORKOUT_SUMMARY_FORMAT_DETAILED = 2,
  /** WORKOUT_SUMMARY_FORMAT_VERBOSE - "4 sets of 8 reps at 100.0 kilograms" */
  WORKOUT_SUMMARY_FORMAT_VERBOSE = 3,
  UNRECOGNIZED = -1,
}

/** Muscle Heatmap visualization styles */
export enum MuscleHeatmapStyle {
  MUSCLE_HEATMAP_STYLE_UNSPECIFIED = 0,
  /** MUSCLE_HEATMAP_STYLE_EMOJI_BARS - "🟪🟪🟪⬜⬜" */
  MUSCLE_HEATMAP_STYLE_EMOJI_BARS = 1,
  /** MUSCLE_HEATMAP_STYLE_PERCENTAGE - "Chest: 80%" */
  MUSCLE_HEATMAP_STYLE_PERCENTAGE = 2,
  /** MUSCLE_HEATMAP_STYLE_TEXT_ONLY - "High: Chest, Medium: Legs" */
  MUSCLE_HEATMAP_STYLE_TEXT_ONLY = 3,
  UNRECOGNIZED = -1,
}

/** Muscle Heatmap coefficient presets */
export enum MuscleHeatmapPreset {
  MUSCLE_HEATMAP_PRESET_UNSPECIFIED = 0,
  /** MUSCLE_HEATMAP_PRESET_STANDARD - Balanced coefficients */
  MUSCLE_HEATMAP_PRESET_STANDARD = 1,
  /** MUSCLE_HEATMAP_PRESET_POWERLIFTING - Emphasize compounds */
  MUSCLE_HEATMAP_PRESET_POWERLIFTING = 2,
  /** MUSCLE_HEATMAP_PRESET_BODYBUILDING - Emphasize isolation */
  MUSCLE_HEATMAP_PRESET_BODYBUILDING = 3,
  UNRECOGNIZED = -1,
}

/** Virtual GPS route options */
export enum VirtualGPSRoute {
  VIRTUAL_GPS_ROUTE_UNSPECIFIED = 0,
  /** VIRTUAL_GPS_ROUTE_LONDON - London Hyde Park (~4km) */
  VIRTUAL_GPS_ROUTE_LONDON = 1,
  /** VIRTUAL_GPS_ROUTE_NYC - NYC Central Park (~10km) */
  VIRTUAL_GPS_ROUTE_NYC = 2,
  UNRECOGNIZED = -1,
}

/** ParkrunResultsState tracks the state of official results enrichment */
export enum ParkrunResultsState {
  PARKRUN_RESULTS_STATE_UNSPECIFIED = 0,
  /** PARKRUN_RESULTS_STATE_PENDING - Awaiting results fetch (auto-populated pending input created) */
  PARKRUN_RESULTS_STATE_PENDING = 1,
  /** PARKRUN_RESULTS_STATE_COMPLETE - Results applied via resume */
  PARKRUN_RESULTS_STATE_COMPLETE = 2,
  /** PARKRUN_RESULTS_STATE_EXPIRED - Polling deadline passed, no results found */
  PARKRUN_RESULTS_STATE_EXPIRED = 3,
  /** PARKRUN_RESULTS_STATE_IMMEDIATE - Results found during initial enrichment (no pending input) */
  PARKRUN_RESULTS_STATE_IMMEDIATE = 4,
  UNRECOGNIZED = -1,
}

/** PipelineRunStatus tracks the overall state of a pipeline execution. */
export enum PipelineRunStatus {
  PIPELINE_RUN_STATUS_UNSPECIFIED = 0,
  /** PIPELINE_RUN_STATUS_RUNNING - In progress */
  PIPELINE_RUN_STATUS_RUNNING = 1,
  /** PIPELINE_RUN_STATUS_SYNCED - All destinations succeeded */
  PIPELINE_RUN_STATUS_SYNCED = 2,
  /** PIPELINE_RUN_STATUS_PARTIAL - Some destinations failed */
  PIPELINE_RUN_STATUS_PARTIAL = 3,
  /** PIPELINE_RUN_STATUS_FAILED - All destinations failed */
  PIPELINE_RUN_STATUS_FAILED = 4,
  /** PIPELINE_RUN_STATUS_PENDING - Waiting for pending input */
  PIPELINE_RUN_STATUS_PENDING = 5,
  /** PIPELINE_RUN_STATUS_SKIPPED - Halted by filter/logic gate */
  PIPELINE_RUN_STATUS_SKIPPED = 6,
  /** PIPELINE_RUN_STATUS_ARCHIVED - Older than TTL, hidden from default views */
  PIPELINE_RUN_STATUS_ARCHIVED = 7,
  /** PIPELINE_RUN_STATUS_TIER_BLOCKED - Blocked by tier limit (upgrade required) */
  PIPELINE_RUN_STATUS_TIER_BLOCKED = 8,
  UNRECOGNIZED = -1,
}

/** DestinationStatus tracks the status of a single destination upload. */
export enum DestinationStatus {
  DESTINATION_STATUS_UNSPECIFIED = 0,
  DESTINATION_STATUS_PENDING = 1,
  DESTINATION_STATUS_SUCCESS = 2,
  DESTINATION_STATUS_FAILED = 3,
  /** DESTINATION_STATUS_SKIPPED - Not in pipeline config or filtered */
  DESTINATION_STATUS_SKIPPED = 4,
  UNRECOGNIZED = -1,
}

export interface UserRecord {
  userId: string;
  createdAt?: Date | undefined;
  integrations?:
    | UserIntegrations
    | undefined;
  /** Field 4 was pipelines (moved to sub-collection users/{userId}/pipelines) */
  fcmTokens: string[];
  /** Pricing tier */
  tier: UserTier;
  /** Athlete trial end date (null = no trial, set to now+30d on signup) */
  trialEndsAt?:
    | Date
    | undefined;
  /** Admin override - grants Pro access without payment */
  isAdmin: boolean;
  /** Monthly sync tracking */
  syncCountThisMonth: number;
  syncCountResetAt?:
    | Date
    | undefined;
  /** Track prevented syncs for marketing/upsell */
  preventedSyncCount: number;
  /** Stripe customer ID for billing */
  stripeCustomerId: string;
  /** Waitlist gate - false until admin enables access */
  accessEnabled: boolean;
  /** User's push notification preferences */
  notificationPreferences?: NotificationPreferences | undefined;
}

/** NotificationPreferences allows users to control what notifications they receive */
export interface NotificationPreferences {
  /** Notify when a pipeline needs user input (e.g., file upload, data selection) */
  notifyPendingInput: boolean;
  /** Notify when an activity is successfully synced to destinations */
  notifyPipelineSuccess: boolean;
  /** Notify when a pipeline fails to process an activity */
  notifyPipelineFailure: boolean;
}

export interface PipelineConfig {
  /** Unique ID (uuid) for tracing */
  id: string;
  /** e.g. "SOURCE_HEVY" */
  source: string;
  enrichers: EnricherConfig[];
  destinations: Destination[];
  /** Optional user-friendly name (e.g., "Morning Gym Sessions") */
  name: string;
  /** When true, pipeline is temporarily disabled and skipped by enricher */
  disabled: boolean;
  /** Source plugin configuration (validated against PluginManifest.config_schema) */
  sourceConfig: { [key: string]: string };
  /** Destination plugin configurations, keyed by destination ID (e.g. "googlesheets") */
  destinationConfigs: { [key: string]: DestinationConfig };
}

export interface PipelineConfig_SourceConfigEntry {
  key: string;
  value: string;
}

export interface PipelineConfig_DestinationConfigsEntry {
  key: string;
  value?: DestinationConfig | undefined;
}

/** Configuration for a single destination plugin */
export interface DestinationConfig {
  config: { [key: string]: string };
}

export interface DestinationConfig_ConfigEntry {
  key: string;
  value: string;
}

/**
 * PluginDefault stores user-level default configuration for a source or destination plugin.
 * Stored in: users/{userId}/plugin_defaults/{pluginId}
 */
export interface PluginDefault {
  /** Registry ID (e.g., "googlesheets", "github") */
  pluginId: string;
  /** Default config values */
  config: { [key: string]: string };
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
}

export interface PluginDefault_ConfigEntry {
  key: string;
  value: string;
}

export interface UserIntegrations {
  hevy?: HevyIntegration | undefined;
  fitbit?: FitbitIntegration | undefined;
  strava?: StravaIntegration | undefined;
  mock?: MockIntegration | undefined;
  parkrun?: ParkrunIntegration | undefined;
  spotify?: SpotifyIntegration | undefined;
  trainingpeaks?: TrainingPeaksIntegration | undefined;
  intervals?: IntervalsIntegration | undefined;
  google?: GoogleIntegration | undefined;
  oura?: OuraIntegration | undefined;
  polar?: PolarIntegration | undefined;
  wahoo?: WahooIntegration | undefined;
  github?: GitHubIntegration | undefined;
}

export interface MockIntegration {
  enabled: boolean;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface HevyIntegration {
  enabled: boolean;
  apiKey: string;
  userId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface FitbitIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  fitbitUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface SourceEnrichmentConfig {
  enrichers: EnricherConfig[];
}

export interface EnricherConfig {
  /** Use strictly typed provider enum instead of string name */
  providerType: EnricherProviderType;
  /**
   * Type-safe configuration map (validated against PluginManifest.config_schema)
   * Keys and values are descriptive strings, not numeric enum values
   */
  typedConfig: { [key: string]: string };
}

export interface EnricherConfig_TypedConfigEntry {
  key: string;
  value: string;
}

export interface StravaIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  athleteId: number;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface ParkrunIntegration {
  enabled: boolean;
  /** Barcode number e.g., "A12345" */
  athleteId: string;
  /** e.g., "www.parkrun.org.uk" */
  countryUrl: string;
  /** GDPR consent for data fetching */
  consentGiven: boolean;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface SpotifyIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  spotifyUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface TrainingPeaksIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?:
    | Date
    | undefined;
  /** TrainingPeaks athlete ID */
  athleteId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface IntervalsIntegration {
  enabled: boolean;
  /** Intervals.icu API key (used as Basic Auth username) */
  apiKey: string;
  /** Intervals.icu athlete ID */
  athleteId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface OuraIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?:
    | Date
    | undefined;
  /** Oura user ID */
  ouraUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface GoogleIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?:
    | Date
    | undefined;
  /** Google user ID */
  googleUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface PolarIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?:
    | Date
    | undefined;
  /** Polar AccessLink user ID */
  polarUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface WahooIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?:
    | Date
    | undefined;
  /** Wahoo Cloud user ID */
  wahooUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface GitHubIntegration {
  enabled: boolean;
  accessToken: string;
  /** GitHub tokens don't expire; placeholder for consistency */
  refreshToken: string;
  expiresAt?:
    | Date
    | undefined;
  /** GitHub user ID */
  githubUserId: string;
  /** GitHub login username */
  githubUsername: string;
  /** Granted OAuth scopes */
  scope: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface ProcessedActivityRecord {
  source: string;
  /** Unique ID from provider */
  externalId: string;
  processedAt?: Date | undefined;
}

export interface Counter {
  /** Key, e.g. "parkrun_bushy" */
  id: string;
  count: number;
  lastUpdated?: Date | undefined;
}

/**
 * Personal Record for tracking PRs across cardio and strength activities
 * Stored in users/{userId}/personal_records/{recordType}
 */
export interface PersonalRecord {
  /** e.g. "fastest_5k", "bench_press_1rm" */
  recordType: string;
  /** The record value (seconds for time, kg for weight, meters for distance) */
  value: number;
  /** "seconds", "kg", "meters", "reps" */
  unit: string;
  /** Activity where this PR was achieved */
  activityId: string;
  achievedAt?: Date | undefined;
  activityType: ActivityType;
  /** Previous PR value (for improvement tracking) */
  previousValue?:
    | number
    | undefined;
  /** Percentage improvement */
  improvement?: number | undefined;
}

/**
 * ShowcasedActivity represents a publicly shareable activity snapshot.
 * Stored in top-level showcased_activities/{showcase_id} collection.
 */
export interface ShowcasedActivity {
  /** Human-readable ID (e.g., "morning-run-2026-01-17") */
  showcaseId: string;
  /** Original FitGlue activity ID */
  activityId: string;
  /** Owner (for tier lookup, not displayed publicly) */
  userId: string;
  /** Activity metadata */
  title: string;
  description: string;
  activityType: ActivityType;
  source: ActivitySource;
  startTime?:
    | Date
    | undefined;
  /** Full activity data for rendering */
  activityData?:
    | StandardizedActivity
    | undefined;
  /** GCS URI for FIT file */
  fitFileUri: string;
  /** Enrichment info */
  appliedEnrichments: string[];
  enrichmentMetadata: { [key: string]: string };
  tags: string[];
  pipelineExecutionId?:
    | string
    | undefined;
  /** Lifecycle */
  createdAt?:
    | Date
    | undefined;
  /** null = never expires (Athlete tier) */
  expiresAt?:
    | Date
    | undefined;
  /** Public attribution */
  ownerDisplayName: string;
  /** GCS URI for pre-parsed activity JSON (avoids Firestore 1MB limit) */
  activityDataUri: string;
}

export interface ShowcasedActivity_EnrichmentMetadataEntry {
  key: string;
  value: string;
}

/**
 * ShowcaseProfileEntry is a lightweight summary of a showcased activity for list display.
 * Stored as part of ShowcaseProfile.entries array.
 */
export interface ShowcaseProfileEntry {
  showcaseId: string;
  title: string;
  activityType: ActivityType;
  source: ActivitySource;
  startTime?:
    | Date
    | undefined;
  /** Optional route thumbnail from enrichment metadata */
  routeThumbnailUrl: string;
  /** For per-activity stat display */
  distanceMeters: number;
  /** For per-activity stat display */
  durationSeconds: number;
  /** Strength stats (per-activity) */
  totalSets: number;
  totalReps: number;
  totalWeightKg: number;
}

/**
 * ShowcaseProfile is a materialized profile document for a user's public showcase homepage.
 * Stored in top-level showcase_profiles/{slug} collection.
 * Athlete tier only - created/updated by the showcase-uploader on each showcase write.
 */
export interface ShowcaseProfile {
  /** URL-safe slug derived from display name */
  slug: string;
  /** Owner (for tier verification, not displayed publicly) */
  userId: string;
  /** Public display name */
  displayName: string;
  /** All showcased activities (lightweight summaries) */
  entries: ShowcaseProfileEntry[];
  /** Aggregate stats (recomputed from entries on each write) */
  totalActivities: number;
  totalDistanceMeters: number;
  totalDurationSeconds: number;
  latestActivityAt?:
    | Date
    | undefined;
  /** Strength aggregates */
  totalSets: number;
  totalReps: number;
  totalWeightKg: number;
  /** Lifecycle */
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
}

/**
 * PipelineRun tracks a complete pipeline execution lifecycle.
 * This is the primary entity for user-facing activity views, replacing the
 * old SynchronizedActivity + executions pattern.
 * Stored in: users/{userId}/pipeline_runs/{pipelineRunId}
 */
export interface PipelineRun {
  /** pipelineExecutionId */
  id: string;
  /** Which pipeline config */
  pipelineId: string;
  /** Generated activity ID */
  activityId: string;
  /** Source Info */
  source: string;
  /** External ID from source */
  sourceActivityId: string;
  /** Activity Summary (denormalized for list display) */
  title: string;
  description: string;
  type: ActivityType;
  startTime?:
    | Date
    | undefined;
  /** Pipeline Status */
  status: PipelineRunStatus;
  createdAt?: Date | undefined;
  updatedAt?:
    | Date
    | undefined;
  /** Booster Executions */
  boosters: BoosterExecution[];
  /** Destination Outcomes */
  destinations: DestinationOutcome[];
  /** Status tracking */
  statusMessage?: string | undefined;
  pendingInputId?:
    | string
    | undefined;
  /** GCS URI: gs://{bucket}/payloads/{userId}/{activityId}.json */
  originalPayloadUri: string;
  /** GCS URI: gs://{bucket}/enriched_events/{userId}/{pipelineRunId}.json */
  enrichedEventUri: string;
}

/** BoosterExecution tracks a single enricher provider's execution. */
export interface BoosterExecution {
  /** e.g., "parkrun-results", "workout-summary" */
  providerName: string;
  /** SUCCESS, SKIPPED, FAILED, WAITING */
  status: string;
  durationMs: number;
  /** Provider-specific output (e.g., skip_reason) */
  metadata: { [key: string]: string };
  error?: string | undefined;
}

export interface BoosterExecution_MetadataEntry {
  key: string;
  value: string;
}

/** DestinationOutcome tracks the result of sending to a single destination. */
export interface DestinationOutcome {
  destination: Destination;
  status: DestinationStatus;
  /** ID from destination platform */
  externalId?: string | undefined;
  error?: string | undefined;
  completedAt?: Date | undefined;
}
