// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/user/billing.proto

/* eslint-disable */
import type { UserTier } from "./profile";

export const protobufPackage = "fitglue.models.user";

/** SubscriptionState tracks the user's billing info, decoupled from core profile. */
export interface SubscriptionState {
  userId: string;
  /** Stripe customer ID for billing */
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  /** Athlete trial end date (null = no trial) */
  trialEndsAt?:
    | Date
    | undefined;
  /** The actual purchased tier (free users won't have this record or it will be free) */
  subscriptionTier: UserTier;
  currentPeriodStart?: Date | undefined;
  currentPeriodEnd?: Date | undefined;
  cancelAtPeriodEnd: boolean;
  /** e.g. "active", "past_due", "canceled" */
  status: string;
}
