// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/user/integration.proto

/* eslint-disable */

export const protobufPackage = "fitglue.models.user";

/** UserIntegrations represents all connected third-party providers. */
export interface UserIntegrations {
  hevy?: HevyIntegration | undefined;
  fitbit?: FitbitIntegration | undefined;
  strava?: StravaIntegration | undefined;
  mock?: MockIntegration | undefined;
  parkrun?: ParkrunIntegration | undefined;
  spotify?: SpotifyIntegration | undefined;
  trainingpeaks?: TrainingPeaksIntegration | undefined;
  intervals?: IntervalsIntegration | undefined;
  google?: GoogleIntegration | undefined;
  oura?: OuraIntegration | undefined;
  polar?: PolarIntegration | undefined;
  wahoo?: WahooIntegration | undefined;
  github?: GitHubIntegration | undefined;
  appleHealth?: AppleHealthIntegration | undefined;
  healthConnect?: HealthConnectIntegration | undefined;
}

export interface MockIntegration {
  enabled: boolean;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface HevyIntegration {
  enabled: boolean;
  apiKey: string;
  userId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface FitbitIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  fitbitUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface StravaIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  athleteId: number;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface ParkrunIntegration {
  enabled: boolean;
  athleteId: string;
  countryUrl: string;
  consentGiven: boolean;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface SpotifyIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  spotifyUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface TrainingPeaksIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  athleteId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface IntervalsIntegration {
  enabled: boolean;
  apiKey: string;
  athleteId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface OuraIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  ouraUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface GoogleIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  googleUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface PolarIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  polarUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface WahooIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  wahooUserId: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface GitHubIntegration {
  enabled: boolean;
  accessToken: string;
  refreshToken: string;
  expiresAt?: Date | undefined;
  githubUserId: string;
  githubUsername: string;
  scope: string;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface AppleHealthIntegration {
  enabled: boolean;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}

export interface HealthConnectIntegration {
  enabled: boolean;
  createdAt?: Date | undefined;
  lastUsedAt?: Date | undefined;
}
