// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/user/profile.proto

/* eslint-disable */
import type { ActivityType } from "../activity/source";

export const protobufPackage = "fitglue.models.user";

export enum UserTier {
  USER_TIER_UNSPECIFIED = 0,
  USER_TIER_HOBBYIST = 1,
  USER_TIER_ATHLETE = 2,
  UNRECOGNIZED = -1,
}

/**
 * UserProfile represents the core user identity and preferences,
 * cleanly separated from billing and integrations.
 */
export interface UserProfile {
  userId: string;
  createdAt?: Date | undefined;
  fcmTokens: string[];
  tier: UserTier;
  isAdmin: boolean;
  /** Monthly sync tracking */
  syncCountThisMonth: number;
  syncCountResetAt?: Date | undefined;
  preventedSyncCount: number;
  /** Waitlist gate - false until admin enables access */
  accessEnabled: boolean;
  /** User's push notification preferences */
  notificationPreferences?: NotificationPreferences | undefined;
  trialEndsAt?: Date | undefined;
  email: string;
  displayName: string;
}

export interface NotificationPreferences {
  notifyPendingInput: boolean;
  notifyPipelineSuccess: boolean;
  notifyPipelineFailure: boolean;
}

export interface Counter {
  /** Key, e.g. "parkrun_bushy" */
  id: string;
  count: number;
  lastUpdated?: Date | undefined;
}

/** Personal Record for tracking PRs across cardio and strength activities */
export interface PersonalRecord {
  /** e.g. "fastest_5k", "bench_press_1rm" */
  recordType: string;
  /** The record value */
  value: number;
  /** "seconds", "kg", "meters", "reps" */
  unit: string;
  /** Activity where this PR was achieved */
  activityId: string;
  achievedAt?: Date | undefined;
  activityType: ActivityType;
  /** Previous PR value */
  previousValue?:
    | number
    | undefined;
  /** Percentage improvement */
  improvement?: number | undefined;
}
