// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/user/profile.proto

/* eslint-disable */
import type { ActivityType } from "../activity/source";

export const protobufPackage = "fitglue.models.user";

export enum NotificationChannel {
  NOTIFICATION_CHANNEL_UNSPECIFIED = 0,
  NOTIFICATION_CHANNEL_PUSH = 1,
  NOTIFICATION_CHANNEL_EMAIL = 2,
  UNRECOGNIZED = -1,
}

export enum UserTier {
  USER_TIER_UNSPECIFIED = 0,
  USER_TIER_HOBBYIST = 1,
  USER_TIER_ATHLETE = 2,
  UNRECOGNIZED = -1,
}

/**
 * UserProfile represents the core user identity and preferences,
 * cleanly separated from billing and integrations.
 */
export interface UserProfile {
  userId: string;
  createdAt?: Date | undefined;
  fcmTokens: string[];
  tier: UserTier;
  isAdmin: boolean;
  /** Monthly sync tracking */
  syncCountThisMonth: number;
  syncCountResetAt?: Date | undefined;
  preventedSyncCount: number;
  /** Waitlist gate - false until admin enables access */
  accessEnabled: boolean;
  /** User's push notification preferences */
  notificationPreferences?: NotificationPreferences | undefined;
  trialEndsAt?: Date | undefined;
  email: string;
  displayName: string;
  /**
   * Streak aggregates — written by streak-tracker enricher rollup on every activity sync.
   * A "streak day" is any calendar day with at least one qualifying activity.
   * Optional; absent means not yet computed.
   */
  currentStreakDays?: number | undefined;
  longestStreakDays?: number | undefined;
}

/**
 * NotificationTypePreference holds which channels are active for one notification type.
 * An empty channels list means the notification type is disabled entirely.
 * A nil/absent preference means "use the default" which is [PUSH].
 */
export interface NotificationTypePreference {
  channels: NotificationChannel[];
}

export interface NotificationPreferences {
  pendingInput?: NotificationTypePreference | undefined;
  pipelineSuccess?: NotificationTypePreference | undefined;
  pipelineFailure?: NotificationTypePreference | undefined;
  connectionAction?: NotificationTypePreference | undefined;
  showcaseRoundup?: NotificationTypePreference | undefined;
}

export interface Counter {
  /** Key, e.g. "parkrun_bushy" */
  id: string;
  count: number;
  lastUpdated?: Date | undefined;
}

/** Personal Record for tracking PRs across cardio and strength activities */
export interface PersonalRecord {
  /** e.g. "fastest_5k", "bench_press_1rm" */
  recordType: string;
  /** The record value */
  value: number;
  /** "seconds", "kg", "meters", "reps" */
  unit: string;
  /** Activity where this PR was achieved */
  activityId: string;
  achievedAt?: Date | undefined;
  activityType: ActivityType;
  /** Previous PR value */
  previousValue?:
    | number
    | undefined;
  /** Percentage improvement */
  improvement?: number | undefined;
}
