// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: services/billing/billing.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";
import type { SubscriptionState } from "../../models/user/billing";
import type { UserTier } from "../../models/user/profile";

export const protobufPackage = "fitglue.services.billing";

export interface GetSubscriptionRequest {
  userId: string;
}

export interface CreateCheckoutSessionRequest {
  userId: string;
  successUrl: string;
  cancelUrl: string;
}

export interface CreateCheckoutSessionResponse {
  sessionUrl: string;
}

export interface HandleWebhookEventRequest {
  payload: Uint8Array;
  signature: string;
}

export interface GetTierStatusRequest {
  userId: string;
}

export interface GetTierStatusResponse {
  effectiveTier: UserTier;
  isTrial: boolean;
}

export interface StartTrialRequest {
  userId: string;
}

export interface CancelSubscriptionRequest {
  userId: string;
}

export interface BillingService {
  GetSubscription(request: GetSubscriptionRequest): Promise<SubscriptionState>;
  CreateCheckoutSession(request: CreateCheckoutSessionRequest): Promise<CreateCheckoutSessionResponse>;
  HandleWebhookEvent(request: HandleWebhookEventRequest): Promise<Empty>;
  GetTierStatus(request: GetTierStatusRequest): Promise<GetTierStatusResponse>;
  StartTrial(request: StartTrialRequest): Promise<SubscriptionState>;
  CancelSubscription(request: CancelSubscriptionRequest): Promise<SubscriptionState>;
}
