// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: services/activity/activity.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";
import type { ShowcaseRoundup } from "../../models/activity/roundup";
import type { StandardizedActivity } from "../../models/activity/standardized";
import type {
  RoundupSettings,
  ShowcasedActivity,
  ShowcaseProfile,
  ShowcaseProfileEntry,
} from "../../models/activity/uploaded";

export const protobufPackage = "fitglue.services.activity";

export interface GetActivityRequest {
  userId: string;
  activityId: string;
}

export interface ListActivitiesRequest {
  userId: string;
  limit: number;
  pageToken: string;
}

export interface ListActivitiesResponse {
  activities: StandardizedActivity[];
  nextPageToken: string;
}

export interface DeleteActivityRequest {
  userId: string;
  activityId: string;
}

export interface GetShowcaseRequest {
  userId: string;
  showcaseId: string;
}

export interface ListShowcasesRequest {
  userId: string;
}

export interface ListShowcasesResponse {
  showcases: ShowcaseProfileEntry[];
}

export interface CreateShowcaseRequest {
  userId: string;
  showcase?: ShowcasedActivity | undefined;
}

export interface UpdateShowcaseRequest {
  userId: string;
  showcaseId: string;
  showcase?: ShowcasedActivity | undefined;
}

export interface DeleteShowcaseRequest {
  userId: string;
  showcaseId: string;
}

export interface ExportDataRequest {
  userId: string;
}

export interface ExportDataResponse {
  downloadUrl: string;
}

export interface ParseFitFileRequest {
  userId: string;
  fitFileContent: Uint8Array;
  title: string;
  description: string;
  pipelineId: string;
}

export interface GetShowcasePreferencesRequest {
  userId: string;
}

export interface UpdateShowcasePreferencesRequest {
  userId: string;
  preferences?: ShowcaseProfile | undefined;
}

export interface GenerateShowcaseImagesRequest {
  userId: string;
  showcaseId: string;
}

export interface GetPublicShowcaseRequest {
  showcaseId: string;
}

/** Showcase Settings Management messages */
export interface GetShowcaseSettingsRequest {
  userId: string;
}

export interface GetShowcaseSettingsResponse {
  profile?: ShowcaseProfile | undefined;
  activities: ShowcaseActivityEntry[];
}

export interface ShowcaseActivityEntry {
  showcaseId: string;
  title: string;
  activityType: string;
  source: string;
  startTime: string;
  createdAt: string;
  inProfile: boolean;
}

export interface UpdateShowcaseSettingsRequest {
  userId: string;
  settings?: ShowcaseProfile | undefined;
}

export interface UpdateShowcaseSlugRequest {
  userId: string;
  slug: string;
}

export interface UpdateShowcaseSlugResponse {
  slug: string;
}

export interface AddShowcaseEntryRequest {
  userId: string;
  showcaseId: string;
  /**
   * destination_count is the number of destinations the activity was uploaded to.
   * Passed by the showcase uploader so the profile entry can reflect the full upload scope.
   */
  destinationCount: number;
  /**
   * route_thumbnail_url is the GCS/CDN URL of the SVG route map generated by the
   * route_thumbnail enricher. Passed through so the profile entry card can show the map.
   */
  routeThumbnailUrl: string;
}

export interface RemoveShowcaseEntryRequest {
  userId: string;
  showcaseId: string;
}

export interface GetShowcaseProfilePictureUploadUrlRequest {
  userId: string;
  contentType: string;
}

export interface GetShowcaseProfilePictureUploadUrlResponse {
  uploadUrl: string;
  publicUrl: string;
  contentType: string;
  maxSizeBytes: number;
}

export interface GetActivityPhotoUploadUrlRequest {
  userId: string;
  activityId: string;
  filename: string;
  contentType: string;
}

export interface GetActivityPhotoUploadUrlResponse {
  uploadUrl: string;
  publicUrl: string;
  contentType: string;
  maxSizeBytes: number;
}

export interface GetPublicShowcaseProfileRequest {
  slug: string;
  page: number;
}

export interface GetPublicShowcaseProfileResponse {
  profile?: ShowcaseProfile | undefined;
  showcases: ShowcasedActivity[];
  totalPages: number;
  currentPage: number;
}

export interface GetActivityStatsRequest {
  userId: string;
}

export interface GetActivityStatsResponse {
  totalActivities: number;
  totalShowcases: number;
  lastActivityAt: string;
  /** Total destination posts this month (one per destination per activity) */
  uploadsThisMonth: number;
  /** Distinct activities successfully synced this month */
  activitiesThisMonth: number;
  /** Distinct activities successfully synced this week */
  activitiesThisWeek: number;
  currentStreakDays: number;
  longestStreakDays: number;
  /** Total destination posts this week (one per destination per activity) */
  uploadsThisWeek: number;
}

export interface GetPublicRoundupRequest {
  slug: string;
  periodKey: string;
}

export interface GetRecentPublicRoundupsRequest {
  slug: string;
  limit: number;
}

export interface GetRecentPublicRoundupsResponse {
  roundups: ShowcaseRoundup[];
}

export interface UpdateRoundupSettingsRequest {
  userId: string;
  settings?: RoundupSettings | undefined;
}

export interface RecomputeRoundupRequest {
  userId: string;
  periodKey: string;
}

export interface ActivityService {
  GetActivity(request: GetActivityRequest): Promise<StandardizedActivity>;
  ListActivities(request: ListActivitiesRequest): Promise<ListActivitiesResponse>;
  DeleteActivity(request: DeleteActivityRequest): Promise<Empty>;
  GetShowcase(request: GetShowcaseRequest): Promise<ShowcasedActivity>;
  ListShowcases(request: ListShowcasesRequest): Promise<ListShowcasesResponse>;
  CreateShowcase(request: CreateShowcaseRequest): Promise<ShowcasedActivity>;
  UpdateShowcase(request: UpdateShowcaseRequest): Promise<ShowcasedActivity>;
  DeleteShowcase(request: DeleteShowcaseRequest): Promise<Empty>;
  ExportData(request: ExportDataRequest): Promise<ExportDataResponse>;
  ParseFitFile(request: ParseFitFileRequest): Promise<StandardizedActivity>;
  GetShowcasePreferences(request: GetShowcasePreferencesRequest): Promise<ShowcaseProfile>;
  UpdateShowcasePreferences(request: UpdateShowcasePreferencesRequest): Promise<ShowcaseProfile>;
  GenerateShowcaseImages(request: GenerateShowcaseImagesRequest): Promise<Empty>;
  GetPublicShowcase(request: GetPublicShowcaseRequest): Promise<ShowcasedActivity>;
  GetPublicShowcaseProfile(request: GetPublicShowcaseProfileRequest): Promise<GetPublicShowcaseProfileResponse>;
  GetActivityStats(request: GetActivityStatsRequest): Promise<GetActivityStatsResponse>;
  /** Showcase Settings Management (profile, entries, picture, slug) */
  GetShowcaseSettings(request: GetShowcaseSettingsRequest): Promise<GetShowcaseSettingsResponse>;
  UpdateShowcaseSettings(request: UpdateShowcaseSettingsRequest): Promise<ShowcaseProfile>;
  UpdateShowcaseSlug(request: UpdateShowcaseSlugRequest): Promise<UpdateShowcaseSlugResponse>;
  AddShowcaseEntry(request: AddShowcaseEntryRequest): Promise<Empty>;
  RemoveShowcaseEntry(request: RemoveShowcaseEntryRequest): Promise<Empty>;
  GetShowcaseProfilePictureUploadUrl(
    request: GetShowcaseProfilePictureUploadUrlRequest,
  ): Promise<GetShowcaseProfilePictureUploadUrlResponse>;
  GetActivityPhotoUploadUrl(request: GetActivityPhotoUploadUrlRequest): Promise<GetActivityPhotoUploadUrlResponse>;
  GetPublicRoundup(request: GetPublicRoundupRequest): Promise<ShowcaseRoundup>;
  GetRecentPublicRoundups(request: GetRecentPublicRoundupsRequest): Promise<GetRecentPublicRoundupsResponse>;
  UpdateRoundupSettings(request: UpdateRoundupSettingsRequest): Promise<ShowcaseProfile>;
  RecomputeRoundup(request: RecomputeRoundupRequest): Promise<ShowcaseRoundup>;
}
