/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2/admin/registration-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Administrative RPCs */
        post: operations["UserService_GenerateRegistrationSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BillingService_HandleWebhookEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/registry/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RegistryService_ListCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/registry/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RegistryService_ListDestinations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/registry/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RegistryService_ListPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/registry/plugins/{pluginId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RegistryService_GetPlugin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/registry/plugins/{pluginId}/icon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RegistryService_GetPluginIcon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/registry/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RegistryService_ListSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserService_CreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/email/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserService_SendPasswordResetEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UserService_DeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/{userId}/booster-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_GetBoosterData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/{userId}/booster-data/{boosterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UserService_SetBoosterData"];
        post?: never;
        delete: operations["UserService_DeleteBoosterData"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/{userId}/counters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_ListCounters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/{userId}/counters/{counterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserService_UpdateCounter"];
        trace?: never;
    };
    "/v2/user/{userId}/email/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UserService_SendEmailChangeVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/{userId}/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Email Auth RPCs */
        post: operations["UserService_SendVerificationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/{userId}/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_ListIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/{userId}/integrations/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_GetIntegration"];
        put: operations["UserService_SetIntegration"];
        post?: never;
        delete: operations["UserService_DeleteIntegration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/{userId}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_GetNotificationPrefs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserService_UpdateNotificationPrefs"];
        trace?: never;
    };
    "/v2/user/{userId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserService_GetProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserService_UpdateProfile"];
        trace?: never;
    };
    "/v2/users/{userId}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ActivityService_ListActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/activities/{activityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ActivityService_GetActivity"];
        put?: never;
        post?: never;
        delete: operations["ActivityService_DeleteActivity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/activities/{activityId}/repost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PipelineService_RepostActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/billing/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BillingService_CancelSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BillingService_CreateCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BillingService_GetSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/billing/tier-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BillingService_GetTierStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/billing/trial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BillingService_StartTrial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/export-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ActivityService_ExportData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/parse-fit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ActivityService_ParseFitFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/pending-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PipelineService_ListPendingInputs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/pending-inputs/{pendingInputId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PipelineService_ResolvePendingInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/pending-inputs/{pendingInputId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PipelineService_SubmitInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/pipeline-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PipelineService_ListPipelineRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/pipeline-runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PipelineService_GetPipelineRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PipelineService_ListPipelines"];
        put?: never;
        post: operations["PipelineService_CreatePipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/pipelines/{pipelineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PipelineService_GetPipeline"];
        put?: never;
        post?: never;
        delete: operations["PipelineService_DeletePipeline"];
        options?: never;
        head?: never;
        patch: operations["PipelineService_UpdatePipeline"];
        trace?: never;
    };
    "/v2/users/{userId}/showcases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ActivityService_ListShowcases"];
        put?: never;
        post: operations["ActivityService_CreateShowcase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/users/{userId}/showcases/{showcaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ActivityService_GetShowcase"];
        put?: never;
        post?: never;
        delete: operations["ActivityService_DeleteShowcase"];
        options?: never;
        head?: never;
        patch: operations["ActivityService_UpdateShowcase"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppleHealthIntegration: {
            enabled?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        BoosterExecution: {
            providerName?: string;
            status?: string;
            durationMs?: string;
            metadata?: {
                [key: string]: string;
            };
            error?: string;
        };
        CancelSubscriptionRequest: {
            userId?: string;
        };
        ConfigFieldDependency: {
            fieldKey?: string;
            values?: string[];
        };
        ConfigFieldOption: {
            value?: string;
            label?: string;
        };
        ConfigFieldSchema: {
            key?: string;
            label?: string;
            description?: string;
            /** Format: enum */
            fieldType?: number;
            required?: boolean;
            defaultValue?: string;
            options?: components["schemas"]["ConfigFieldOption"][];
            validation?: components["schemas"]["ConfigFieldValidation"];
            dependsOn?: components["schemas"]["ConfigFieldDependency"];
            keyOptions?: components["schemas"]["ConfigFieldOption"][];
            valueOptions?: components["schemas"]["ConfigFieldOption"][];
            dynamicSource?: string;
            valueDynamicSource?: string;
        };
        ConfigFieldValidation: {
            /** Format: int32 */
            minLength?: number;
            /** Format: int32 */
            maxLength?: number;
            pattern?: string;
            /** Format: double */
            minValue?: number;
            /** Format: double */
            maxValue?: number;
        };
        Counter: {
            id?: string;
            count?: string;
            /** Format: date-time */
            lastUpdated?: string;
        };
        CreateCheckoutSessionRequest: {
            userId?: string;
            successUrl?: string;
            cancelUrl?: string;
        };
        CreateCheckoutSessionResponse: {
            sessionUrl?: string;
        };
        CreateUserRequest: {
            userId?: string;
        };
        DestinationConfig: {
            config?: {
                [key: string]: string;
            };
            excludedEnrichers?: string[];
        };
        DestinationOutcome: {
            /** Format: enum */
            destination?: number;
            /** Format: enum */
            status?: number;
            externalId?: string;
            error?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        EnricherConfig: {
            /** Format: enum */
            providerType?: number;
            typedConfig?: {
                [key: string]: string;
            };
        };
        ExportDataRequest: {
            userId?: string;
        };
        ExportDataResponse: {
            downloadUrl?: string;
        };
        FitbitIntegration: {
            enabled?: boolean;
            accessToken?: string;
            refreshToken?: string;
            /** Format: date-time */
            expiresAt?: string;
            fitbitUserId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        GenerateRegistrationSummaryRequest: {
            /** @description Optional date override (e.g. "2026-02-23"), uses previous 24 hours if empty */
            dateOverride?: string;
        };
        GetBoosterDataResponse: {
            /** @description Map of booster_id to its JSON payload */
            data?: {
                [key: string]: Record<string, never>;
            };
        };
        GetIntegrationResponse: {
            /**
             * @description Uses a generic bytes payload or structured oneOf depending on how we decide to send it
             *      For now, returning the whole UserIntegrations tree is easiest
             */
            integrations?: components["schemas"]["UserIntegrations"];
        };
        GetPluginIconResponse: {
            /** Format: bytes */
            iconData?: string;
            contentType?: string;
        };
        GetTierStatusResponse: {
            /** Format: enum */
            effectiveTier?: number;
            isTrial?: boolean;
        };
        GitHubIntegration: {
            enabled?: boolean;
            accessToken?: string;
            refreshToken?: string;
            /** Format: date-time */
            expiresAt?: string;
            githubUserId?: string;
            githubUsername?: string;
            scope?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        GoogleIntegration: {
            enabled?: boolean;
            accessToken?: string;
            refreshToken?: string;
            /** Format: date-time */
            expiresAt?: string;
            googleUserId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        /** @description Contains an arbitrary serialized message along with a @type that describes the type of the serialized message. */
        GoogleProtobufAny: {
            /** @description The type of the serialized message. */
            "@type"?: string;
        } & {
            [key: string]: unknown;
        };
        HandleWebhookEventRequest: {
            /** Format: bytes */
            payload?: string;
            signature?: string;
        };
        HealthConnectIntegration: {
            enabled?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        HevyIntegration: {
            enabled?: boolean;
            apiKey?: string;
            userId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        IntervalsIntegration: {
            enabled?: boolean;
            apiKey?: string;
            athleteId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        Lap: {
            /** Format: date-time */
            startTime?: string;
            /** Format: double */
            totalElapsedTime?: number;
            /** Format: double */
            totalDistance?: number;
            records?: components["schemas"]["Record"][];
            exerciseName?: string;
            intensity?: string;
        };
        ListActivitiesResponse: {
            activities?: components["schemas"]["StandardizedActivity"][];
            nextPageToken?: string;
        };
        ListCategoriesResponse: {
            categories?: string[];
        };
        ListCountersResponse: {
            counters?: components["schemas"]["Counter"][];
        };
        ListDestinationsResponse: {
            destinations?: components["schemas"]["PluginManifest"][];
        };
        ListPendingInputsResponse: {
            inputs?: components["schemas"]["PendingInput"][];
        };
        ListPipelineRunsResponse: {
            runs?: components["schemas"]["PipelineRun"][];
        };
        ListPipelinesResponse: {
            pipelines?: components["schemas"]["PipelineConfig"][];
        };
        ListPluginsResponse: {
            plugins?: components["schemas"]["PluginManifest"][];
        };
        ListShowcasesResponse: {
            showcases?: components["schemas"]["ShowcaseProfileEntry"][];
        };
        ListSourcesResponse: {
            sources?: components["schemas"]["PluginManifest"][];
        };
        MockIntegration: {
            enabled?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        NotificationPreferences: {
            notifyPendingInput?: boolean;
            notifyPipelineSuccess?: boolean;
            notifyPipelineFailure?: boolean;
        };
        OuraIntegration: {
            enabled?: boolean;
            accessToken?: string;
            refreshToken?: string;
            /** Format: date-time */
            expiresAt?: string;
            ouraUserId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        ParkrunIntegration: {
            enabled?: boolean;
            athleteId?: string;
            countryUrl?: string;
            consentGiven?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        ParseFitFileRequest: {
            userId?: string;
            /** Format: bytes */
            fitFileContent?: string;
            title?: string;
            description?: string;
            pipelineId?: string;
        };
        PendingInput: {
            activityId?: string;
            userId?: string;
            /** Format: enum */
            status?: number;
            requiredFields?: string[];
            inputData?: {
                [key: string]: string;
            };
            originalPayloadUri?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            continuedWithoutResolution?: boolean;
            linkedActivityId?: string;
            pipelineId?: string;
            enricherProviderId?: string;
            autoPopulated?: boolean;
            /** Format: date-time */
            autoDeadline?: string;
            providerMetadata?: {
                [key: string]: string;
            };
        };
        PipelineConfig: {
            id?: string;
            source?: string;
            enrichers?: components["schemas"]["EnricherConfig"][];
            destinations?: number[];
            name?: string;
            disabled?: boolean;
            sourceConfig?: {
                [key: string]: string;
            };
            destinationConfigs?: {
                [key: string]: components["schemas"]["DestinationConfig"];
            };
        };
        PipelineRun: {
            id?: string;
            pipelineId?: string;
            activityId?: string;
            source?: string;
            sourceActivityId?: string;
            title?: string;
            description?: string;
            /** Format: enum */
            type?: number;
            /** Format: date-time */
            startTime?: string;
            /** Format: enum */
            status?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            boosters?: components["schemas"]["BoosterExecution"][];
            destinations?: components["schemas"]["DestinationOutcome"][];
            statusMessage?: string;
            pendingInputId?: string;
            originalPayloadUri?: string;
            enrichedEventUri?: string;
        };
        PluginManifest: {
            id?: string;
            /** Format: enum */
            type?: number;
            name?: string;
            description?: string;
            icon?: string;
            configSchema?: components["schemas"]["ConfigFieldSchema"][];
            requiredIntegrations?: string[];
            enabled?: boolean;
            /** Format: int32 */
            enricherProviderType?: number;
            /** Format: int32 */
            destinationType?: number;
            marketingDescription?: string;
            features?: string[];
            transformations?: components["schemas"]["Transformation"][];
            useCases?: string[];
            externalUrlTemplate?: string;
            requiredTier?: string;
            category?: string;
            /** Format: int32 */
            sortOrder?: number;
            isPremium?: boolean;
            /** Format: int32 */
            popularityScore?: number;
            iconType?: string;
            iconPath?: string;
            isTemporarilyUnavailable?: boolean;
            allowMultipleInstances?: boolean;
        };
        PolarIntegration: {
            enabled?: boolean;
            accessToken?: string;
            refreshToken?: string;
            /** Format: date-time */
            expiresAt?: string;
            polarUserId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        Record: {
            /** Format: date-time */
            timestamp?: string;
            /** Format: int32 */
            heartRate?: number;
            /** Format: int32 */
            power?: number;
            /** Format: int32 */
            cadence?: number;
            /** Format: double */
            speed?: number;
            /** Format: double */
            altitude?: number;
            /** Format: double */
            positionLat?: number;
            /** Format: double */
            positionLong?: number;
            /** Format: int32 */
            groundContactTime?: number;
            /** Format: int32 */
            verticalOscillation?: number;
            /** Format: int32 */
            verticalRatio?: number;
            /** Format: double */
            stepLength?: number;
        };
        RepostActivityRequest: {
            userId?: string;
            activityId?: string;
        };
        ResolvePendingInputRequest: {
            userId?: string;
            pendingInputId?: string;
        };
        SendEmailChangeVerificationRequest: {
            userId?: string;
            newEmail?: string;
        };
        SendPasswordResetEmailRequest: {
            email?: string;
        };
        SendVerificationEmailRequest: {
            userId?: string;
        };
        Session: {
            /** Format: date-time */
            startTime?: string;
            /** Format: double */
            totalElapsedTime?: number;
            /** Format: double */
            totalDistance?: number;
            laps?: components["schemas"]["Lap"][];
            strengthSets?: components["schemas"]["StrengthSet"][];
            /** Format: double */
            totalCalories?: number;
            /** Format: int32 */
            avgHeartRate?: number;
            /** Format: int32 */
            maxHeartRate?: number;
        };
        SetIntegrationRequest: {
            userId?: string;
            provider?: string;
        };
        ShowcaseProfileEntry: {
            showcaseId?: string;
            title?: string;
            /** Format: enum */
            activityType?: number;
            /** Format: enum */
            source?: number;
            /** Format: date-time */
            startTime?: string;
            routeThumbnailUrl?: string;
            /** Format: double */
            distanceMeters?: number;
            /** Format: double */
            durationSeconds?: number;
            /** Format: int32 */
            totalSets?: number;
            /** Format: int32 */
            totalReps?: number;
            /** Format: double */
            totalWeightKg?: number;
        };
        /** @description ShowcasedActivity represents a publicly shareable activity snapshot. */
        ShowcasedActivity: {
            showcaseId?: string;
            activityId?: string;
            userId?: string;
            title?: string;
            description?: string;
            /** Format: enum */
            activityType?: number;
            /** Format: enum */
            source?: number;
            /** Format: date-time */
            startTime?: string;
            activityData?: components["schemas"]["StandardizedActivity"];
            fitFileUri?: string;
            appliedEnrichments?: string[];
            enrichmentMetadata?: {
                [key: string]: string;
            };
            tags?: string[];
            pipelineExecutionId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            ownerDisplayName?: string;
            activityDataUri?: string;
        };
        SpotifyIntegration: {
            enabled?: boolean;
            accessToken?: string;
            refreshToken?: string;
            /** Format: date-time */
            expiresAt?: string;
            spotifyUserId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        StandardizedActivity: {
            /** Format: enum */
            source?: number;
            externalId?: string;
            userId?: string;
            /** Format: date-time */
            startTime?: string;
            name?: string;
            /** Format: enum */
            type?: number;
            sessions?: components["schemas"]["Session"][];
            description?: string;
            tags?: string[];
            notes?: string;
            timeMarkers?: components["schemas"]["TimeMarker"][];
            workout?: components["schemas"]["WorkoutDefinition"];
        };
        StartTrialRequest: {
            userId?: string;
        };
        /** @description The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors). */
        Status: {
            /**
             * Format: int32
             * @description The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
             */
            code?: number;
            /** @description A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client. */
            message?: string;
            /** @description A list of messages that carry the error details.  There is a common set of message types for APIs to use. */
            details?: components["schemas"]["GoogleProtobufAny"][];
        };
        StravaIntegration: {
            enabled?: boolean;
            accessToken?: string;
            refreshToken?: string;
            /** Format: date-time */
            expiresAt?: string;
            athleteId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        StrengthSet: {
            exerciseName?: string;
            /** Format: int32 */
            reps?: number;
            /** Format: double */
            weightKg?: number;
            /** Format: date-time */
            startTime?: string;
            /** Format: int32 */
            durationSeconds?: number;
            notes?: string;
            supersetId?: string;
            /** Format: enum */
            primaryMuscleGroup?: number;
            secondaryMuscleGroups?: number[];
            /** Format: double */
            distanceMeters?: number;
            setType?: string;
        };
        SubmitInputRequest: {
            userId?: string;
            pendingInputId?: string;
            inputData?: {
                [key: string]: string;
            };
        };
        /** @description SubscriptionState tracks the user's billing info, decoupled from core profile. */
        SubscriptionState: {
            userId?: string;
            /** @description Stripe customer ID for billing */
            stripeCustomerId?: string;
            stripeSubscriptionId?: string;
            /**
             * Format: date-time
             * @description Athlete trial end date (null = no trial)
             */
            trialEndsAt?: string;
            /**
             * Format: enum
             * @description The actual purchased tier (free users won't have this record or it will be free)
             */
            subscriptionTier?: number;
            /** Format: date-time */
            currentPeriodStart?: string;
            /** Format: date-time */
            currentPeriodEnd?: string;
            cancelAtPeriodEnd?: boolean;
            status?: string;
        };
        TimeMarker: {
            /** Format: date-time */
            timestamp?: string;
            label?: string;
            markerType?: string;
        };
        TrainingPeaksIntegration: {
            enabled?: boolean;
            accessToken?: string;
            refreshToken?: string;
            /** Format: date-time */
            expiresAt?: string;
            athleteId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        Transformation: {
            field?: string;
            label?: string;
            before?: string;
            after?: string;
            visualType?: string;
            afterHtml?: string;
        };
        UpdateCounterRequest: {
            userId?: string;
            counterId?: string;
            count?: string;
        };
        /** @description UserIntegrations represents all connected third-party providers. */
        UserIntegrations: {
            hevy?: components["schemas"]["HevyIntegration"];
            fitbit?: components["schemas"]["FitbitIntegration"];
            strava?: components["schemas"]["StravaIntegration"];
            mock?: components["schemas"]["MockIntegration"];
            parkrun?: components["schemas"]["ParkrunIntegration"];
            spotify?: components["schemas"]["SpotifyIntegration"];
            trainingpeaks?: components["schemas"]["TrainingPeaksIntegration"];
            intervals?: components["schemas"]["IntervalsIntegration"];
            google?: components["schemas"]["GoogleIntegration"];
            oura?: components["schemas"]["OuraIntegration"];
            polar?: components["schemas"]["PolarIntegration"];
            wahoo?: components["schemas"]["WahooIntegration"];
            github?: components["schemas"]["GitHubIntegration"];
            appleHealth?: components["schemas"]["AppleHealthIntegration"];
            healthConnect?: components["schemas"]["HealthConnectIntegration"];
        };
        /**
         * @description UserProfile represents the core user identity and preferences,
         *      cleanly separated from billing and integrations.
         */
        UserProfile: {
            userId?: string;
            /** Format: date-time */
            createdAt?: string;
            fcmTokens?: string[];
            /** Format: enum */
            tier?: number;
            isAdmin?: boolean;
            /**
             * Format: int32
             * @description Monthly sync tracking
             */
            syncCountThisMonth?: number;
            /** Format: date-time */
            syncCountResetAt?: string;
            /** Format: int32 */
            preventedSyncCount?: number;
            /** @description Waitlist gate - false until admin enables access */
            accessEnabled?: boolean;
            /** @description User's push notification preferences */
            notificationPreferences?: components["schemas"]["NotificationPreferences"];
            /** Format: date-time */
            trialEndsAt?: string;
        };
        WahooIntegration: {
            enabled?: boolean;
            accessToken?: string;
            refreshToken?: string;
            /** Format: date-time */
            expiresAt?: string;
            wahooUserId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        WorkoutDefinition: {
            name?: string;
            steps?: components["schemas"]["WorkoutStep"][];
        };
        WorkoutStep: {
            intensity?: string;
            durationType?: string;
            /** Format: uint32 */
            durationValue?: number;
            targetType?: string;
            /** Format: uint32 */
            targetLow?: number;
            /** Format: uint32 */
            targetHigh?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UserService_GenerateRegistrationSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRegistrationSummaryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BillingService_HandleWebhookEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandleWebhookEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    RegistryService_ListCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCategoriesResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    RegistryService_ListDestinations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDestinationsResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    RegistryService_ListPlugins: {
        parameters: {
            query?: {
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPluginsResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    RegistryService_GetPlugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pluginId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginManifest"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    RegistryService_GetPluginIcon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pluginId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPluginIconResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    RegistryService_ListSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSourcesResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_CreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_SendPasswordResetEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendPasswordResetEmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_DeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_GetBoosterData: {
        parameters: {
            query?: {
                boosterId?: string;
            };
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetBoosterDataResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_SetBoosterData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                boosterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_DeleteBoosterData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                boosterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_ListCounters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCountersResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_UpdateCounter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                counterId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCounterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Counter"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_SendEmailChangeVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendEmailChangeVerificationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_SendVerificationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendVerificationEmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_ListIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserIntegrations"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_GetIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetIntegrationResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_SetIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetIntegrationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_DeleteIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_GetNotificationPrefs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferences"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_UpdateNotificationPrefs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreferences"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferences"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_GetProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    UserService_UpdateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfile"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ActivityService_ListActivities: {
        parameters: {
            query?: {
                limit?: number;
                pageToken?: string;
            };
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListActivitiesResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ActivityService_GetActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                activityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardizedActivity"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ActivityService_DeleteActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                activityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PipelineService_RepostActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                activityId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepostActivityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BillingService_CancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelSubscriptionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionState"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BillingService_CreateCheckoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCheckoutSessionResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BillingService_GetSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionState"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BillingService_GetTierStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTierStatusResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BillingService_StartTrial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTrialRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionState"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ActivityService_ExportData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportDataRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportDataResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ActivityService_ParseFitFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseFitFileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardizedActivity"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PipelineService_ListPendingInputs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPendingInputsResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PipelineService_ResolvePendingInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                pendingInputId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolvePendingInputRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PipelineService_SubmitInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                pendingInputId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitInputRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PipelineService_ListPipelineRuns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPipelineRunsResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PipelineService_GetPipelineRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRun"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PipelineService_ListPipelines: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPipelinesResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PipelineService_CreatePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineConfig"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PipelineService_GetPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                pipelineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineConfig"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PipelineService_DeletePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                pipelineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PipelineService_UpdatePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                pipelineId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineConfig"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ActivityService_ListShowcases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListShowcasesResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ActivityService_CreateShowcase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShowcasedActivity"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowcasedActivity"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ActivityService_GetShowcase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                showcaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowcasedActivity"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ActivityService_DeleteShowcase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                showcaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ActivityService_UpdateShowcase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                showcaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShowcasedActivity"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowcasedActivity"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
}
