export type ActivityCategory =
  | 'cardio'
  | 'strength'
  | 'outdoor'
  | 'cycling'
  | 'water'
  | 'winter'
  | 'mind'
  | 'sport'
  | 'general';

export const ACTIVITY_TYPE_ICONS: Record<string, string> = {
  ACTIVITY_TYPE_RUN: '🏃',
  ACTIVITY_TYPE_TRAIL_RUN: '🏔️',
  ACTIVITY_TYPE_VIRTUAL_RUN: '🏃',
  ACTIVITY_TYPE_WALK: '🚶',
  ACTIVITY_TYPE_HIKE: '🥾',
  ACTIVITY_TYPE_RIDE: '🚴',
  ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE: '🚵',
  ACTIVITY_TYPE_GRAVEL_RIDE: '🚴',
  ACTIVITY_TYPE_EBIKE_RIDE: '⚡',
  ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE: '⚡',
  ACTIVITY_TYPE_VIRTUAL_RIDE: '🚴',
  ACTIVITY_TYPE_SWIM: '🏊',
  ACTIVITY_TYPE_ROWING: '🚣',
  ACTIVITY_TYPE_VIRTUAL_ROW: '🚣',
  ACTIVITY_TYPE_KAYAKING: '🛶',
  ACTIVITY_TYPE_STAND_UP_PADDLING: '🏄',
  ACTIVITY_TYPE_SURFING: '🏄',
  ACTIVITY_TYPE_WEIGHT_TRAINING: '🏋️',
  ACTIVITY_TYPE_CROSSFIT: '🏋️',
  ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING: '⚡',
  ACTIVITY_TYPE_YOGA: '🧘',
  ACTIVITY_TYPE_PILATES: '🧘',
  ACTIVITY_TYPE_ELLIPTICAL: '🔄',
  ACTIVITY_TYPE_STAIR_STEPPER: '🪜',
  ACTIVITY_TYPE_ALPINE_SKI: '⛷️',
  ACTIVITY_TYPE_NORDIC_SKI: '🎿',
  ACTIVITY_TYPE_BACKCOUNTRY_SKI: '🎿',
  ACTIVITY_TYPE_SNOWBOARD: '🏂',
  ACTIVITY_TYPE_SNOWSHOE: '🥾',
  ACTIVITY_TYPE_ROCK_CLIMBING: '🧗',
  ACTIVITY_TYPE_GOLF: '⛳',
  ACTIVITY_TYPE_TENNIS: '🎾',
  ACTIVITY_TYPE_BADMINTON: '🏸',
  ACTIVITY_TYPE_TABLE_TENNIS: '🏓',
  ACTIVITY_TYPE_SOCCER: '⚽',
  ACTIVITY_TYPE_PICKLEBALL: '🏓',
  ACTIVITY_TYPE_SQUASH: '🎾',
  ACTIVITY_TYPE_RACQUETBALL: '🎾',
  ACTIVITY_TYPE_SAIL: '⛵',
  ACTIVITY_TYPE_WINDSURF: '🪁',
  ACTIVITY_TYPE_KITESURF: '🪁',
  ACTIVITY_TYPE_WORKOUT: '🏃',
};

export const ACTIVITY_CATEGORY: Record<string, ActivityCategory> = {
  ACTIVITY_TYPE_RUN: 'cardio',
  ACTIVITY_TYPE_TRAIL_RUN: 'outdoor',
  ACTIVITY_TYPE_VIRTUAL_RUN: 'cardio',
  ACTIVITY_TYPE_WALK: 'cardio',
  ACTIVITY_TYPE_HIKE: 'outdoor',
  ACTIVITY_TYPE_RIDE: 'cycling',
  ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE: 'cycling',
  ACTIVITY_TYPE_GRAVEL_RIDE: 'cycling',
  ACTIVITY_TYPE_EBIKE_RIDE: 'cycling',
  ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE: 'cycling',
  ACTIVITY_TYPE_VIRTUAL_RIDE: 'cycling',
  ACTIVITY_TYPE_SWIM: 'water',
  ACTIVITY_TYPE_ROWING: 'water',
  ACTIVITY_TYPE_VIRTUAL_ROW: 'water',
  ACTIVITY_TYPE_KAYAKING: 'water',
  ACTIVITY_TYPE_STAND_UP_PADDLING: 'water',
  ACTIVITY_TYPE_SURFING: 'water',
  ACTIVITY_TYPE_CANOEING: 'water',
  ACTIVITY_TYPE_WINDSURF: 'water',
  ACTIVITY_TYPE_KITESURF: 'water',
  ACTIVITY_TYPE_SAIL: 'water',
  ACTIVITY_TYPE_WEIGHT_TRAINING: 'strength',
  ACTIVITY_TYPE_CROSSFIT: 'strength',
  ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING: 'strength',
  ACTIVITY_TYPE_ELLIPTICAL: 'cardio',
  ACTIVITY_TYPE_STAIR_STEPPER: 'cardio',
  ACTIVITY_TYPE_YOGA: 'mind',
  ACTIVITY_TYPE_PILATES: 'mind',
  ACTIVITY_TYPE_ALPINE_SKI: 'winter',
  ACTIVITY_TYPE_NORDIC_SKI: 'winter',
  ACTIVITY_TYPE_BACKCOUNTRY_SKI: 'winter',
  ACTIVITY_TYPE_SNOWBOARD: 'winter',
  ACTIVITY_TYPE_SNOWSHOE: 'winter',
  ACTIVITY_TYPE_ICE_SKATE: 'winter',
  ACTIVITY_TYPE_ROCK_CLIMBING: 'outdoor',
  ACTIVITY_TYPE_GOLF: 'sport',
  ACTIVITY_TYPE_TENNIS: 'sport',
  ACTIVITY_TYPE_BADMINTON: 'sport',
  ACTIVITY_TYPE_TABLE_TENNIS: 'sport',
  ACTIVITY_TYPE_SOCCER: 'sport',
  ACTIVITY_TYPE_PICKLEBALL: 'sport',
  ACTIVITY_TYPE_SQUASH: 'sport',
  ACTIVITY_TYPE_RACQUETBALL: 'sport',
};

export function getActivityIcon(type: string | undefined): string {
  if (!type) return '🏅';
  return ACTIVITY_TYPE_ICONS[type] ?? '🏅';
}

export function getActivityCategory(type: string | undefined): ActivityCategory {
  if (!type) return 'general';
  return ACTIVITY_CATEGORY[type] ?? 'general';
}
