// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/events/pipeline.proto

/* eslint-disable */
import type { ActivitySource, ActivityType } from "../activity/source";
import type { StandardizedActivity } from "../activity/standardized";
import type { DestinationType } from "../plugin/provider";

export const protobufPackage = "fitglue.models.events";

export enum CloudEventType {
  CLOUD_EVENT_TYPE_UNSPECIFIED = 0,
  CLOUD_EVENT_TYPE_ACTIVITY_CREATED = 1,
  CLOUD_EVENT_TYPE_ACTIVITY_ENRICHED = 2,
  CLOUD_EVENT_TYPE_JOB_ROUTED = 3,
  CLOUD_EVENT_TYPE_FITBIT_NOTIFICATION = 4,
  CLOUD_EVENT_TYPE_ENRICHMENT_LAG = 5,
  CLOUD_EVENT_TYPE_INPUT_RESOLVED = 6,
  CLOUD_EVENT_TYPE_PARKRUN_RESULTS = 7,
  UNRECOGNIZED = -1,
}

export enum CloudEventSource {
  CLOUD_EVENT_SOURCE_UNSPECIFIED = 0,
  CLOUD_EVENT_SOURCE_HEVY = 1,
  CLOUD_EVENT_SOURCE_FITBIT_WEBHOOK = 2,
  CLOUD_EVENT_SOURCE_FITBIT_INGEST = 3,
  CLOUD_EVENT_SOURCE_ENRICHER = 4,
  CLOUD_EVENT_SOURCE_ROUTER = 5,
  CLOUD_EVENT_SOURCE_INPUTS_HANDLER = 6,
  CLOUD_EVENT_SOURCE_PARKRUN_RESULTS = 7,
  CLOUD_EVENT_SOURCE_FILE_UPLOAD = 8,
  CLOUD_EVENT_SOURCE_STRAVA = 9,
  CLOUD_EVENT_SOURCE_OURA = 10,
  CLOUD_EVENT_SOURCE_POLAR_WEBHOOK = 11,
  CLOUD_EVENT_SOURCE_WAHOO = 12,
  CLOUD_EVENT_SOURCE_PIPELINE_SPLITTER = 13,
  CLOUD_EVENT_SOURCE_GITHUB = 14,
  CLOUD_EVENT_SOURCE_APPLE_HEALTH = 15,
  CLOUD_EVENT_SOURCE_HEALTH_CONNECT = 16,
  CLOUD_EVENT_SOURCE_MOCK = 99,
  UNRECOGNIZED = -1,
}

export interface ActivityPayload {
  source: ActivitySource;
  userId: string;
  timestamp?: Date | undefined;
  originalPayloadJson: string;
  metadata: { [key: string]: string };
  standardizedActivity?: StandardizedActivity | undefined;
  pipelineExecutionId?: string | undefined;
  activityId?: string | undefined;
  pipelineId?: string | undefined;
  isResume: boolean;
  resumeOnlyEnrichers: string[];
  useUpdateMethod: boolean;
  resumePendingInputId?: string | undefined;
  originDestination?: string | undefined;
}

export interface ActivityPayload_MetadataEntry {
  key: string;
  value: string;
}

export interface EnrichedActivityEvent {
  activityId: string;
  userId: string;
  pipelineId: string;
  fitFileUri: string;
  name: string;
  description: string;
  activityType: ActivityType;
  startTime?: Date | undefined;
  source: ActivitySource;
  activityData?: StandardizedActivity | undefined;
  appliedEnrichments: string[];
  enrichmentMetadata: { [key: string]: string };
  destinations: DestinationType[];
  tags: string[];
  pipelineExecutionId?: string | undefined;
  activityDataUri: string;
}

export interface EnrichedActivityEvent_EnrichmentMetadataEntry {
  key: string;
  value: string;
}

export interface MessagePublishedData {
  data: Uint8Array;
  attributes: { [key: string]: string };
  messageId: string;
  publishTime: string;
}

export interface MessagePublishedData_AttributesEntry {
  key: string;
  value: string;
}
