// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: services/registry/registry.proto

/* eslint-disable */
import type { PluginManifest } from "../../models/plugin/manifest";

export const protobufPackage = "fitglue.services.registry";

export interface ListPluginsRequest {
  category: string;
}

export interface ListPluginsResponse {
  plugins: PluginManifest[];
}

export interface GetPluginRequest {
  pluginId: string;
}

export interface ListCategoriesRequest {
}

export interface ListCategoriesResponse {
  categories: string[];
}

export interface GetPluginIconRequest {
  pluginId: string;
}

export interface GetPluginIconResponse {
  iconData: Uint8Array;
  contentType: string;
}

export interface ListSourcesRequest {
}

export interface ListSourcesResponse {
  sources: PluginManifest[];
}

export interface ListDestinationsRequest {
}

export interface ListDestinationsResponse {
  destinations: PluginManifest[];
}

export interface RegistryService {
  ListPlugins(request: ListPluginsRequest): Promise<ListPluginsResponse>;
  GetPlugin(request: GetPluginRequest): Promise<PluginManifest>;
  ListCategories(request: ListCategoriesRequest): Promise<ListCategoriesResponse>;
  GetPluginIcon(request: GetPluginIconRequest): Promise<GetPluginIconResponse>;
  ListSources(request: ListSourcesRequest): Promise<ListSourcesResponse>;
  ListDestinations(request: ListDestinationsRequest): Promise<ListDestinationsResponse>;
}
