// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: services/user/user.proto

/* eslint-disable */
import type { Empty } from "../../google/protobuf/empty";
import type { UserIntegrations } from "../../models/user/integration";
import type { Counter, NotificationPreferences, PersonalRecord, UserProfile } from "../../models/user/profile";

export const protobufPackage = "fitglue.services.user";

export interface ResolveUserByIntegrationRequest {
  provider: string;
  providerUid: string;
}

export interface ResolveUserByIntegrationResponse {
  profile?: UserProfile | undefined;
}

export interface SendVerificationEmailRequest {
  userId: string;
}

export interface SendPasswordResetEmailRequest {
  email: string;
}

export interface SendEmailChangeVerificationRequest {
  userId: string;
  newEmail: string;
}

export interface SendWelcomeEmailRequest {
  userId: string;
}

export interface GenerateRegistrationSummaryRequest {
  /** Optional date override (e.g. "2026-02-23"), uses previous 24 hours if empty */
  dateOverride: string;
}

export interface CreateUserRequest {
  userId: string;
}

export interface ListUsersRequest {
  limit: number;
  pageToken: string;
}

export interface ListUsersResponse {
  users: UserProfile[];
  nextPageToken: string;
}

export interface GetProfileRequest {
  userId: string;
}

export interface UpdateProfileRequest {
  userId: string;
  profile?: UserProfile | undefined;
}

export interface GetIntegrationRequest {
  userId: string;
  provider: string;
}

export interface GetIntegrationResponse {
  /**
   * Uses a generic bytes payload or structured oneOf depending on how we decide to send it
   * For now, returning the whole UserIntegrations tree is easiest
   */
  integrations?: UserIntegrations | undefined;
}

export interface SetIntegrationRequest {
  userId: string;
  provider: string;
  integrationData?: { [key: string]: any } | undefined;
}

export interface DeleteIntegrationRequest {
  userId: string;
  provider: string;
}

export interface ListIntegrationsRequest {
  userId: string;
}

export interface GetNotificationPrefsRequest {
  userId: string;
}

export interface UpdateNotificationPrefsRequest {
  userId: string;
  prefs?: NotificationPreferences | undefined;
}

export interface ListCountersRequest {
  userId: string;
}

export interface ListCountersResponse {
  counters: Counter[];
}

export interface UpdateCounterRequest {
  userId: string;
  counterId: string;
  count: number;
}

export interface DeleteUserRequest {
  userId: string;
}

export interface GetBoosterDataRequest {
  userId: string;
  /** Optional: If empty, returns all booster data for the user */
  boosterId: string;
}

export interface GetBoosterDataResponse {
  /** Map of booster_id to its JSON payload */
  data: { [key: string]: { [key: string]: any } | undefined };
}

export interface GetBoosterDataResponse_DataEntry {
  key: string;
  value?: { [key: string]: any } | undefined;
}

export interface SetBoosterDataRequest {
  userId: string;
  boosterId: string;
  data?: { [key: string]: any } | undefined;
}

export interface DeleteBoosterDataRequest {
  userId: string;
  boosterId: string;
}

/** Personal Records */
export interface ListPersonalRecordsRequest {
  userId: string;
}

export interface ListPersonalRecordsResponse {
  records: PersonalRecord[];
}

export interface SetPersonalRecordRequest {
  userId: string;
  recordType: string;
  value: number;
  unit: string;
  activityId: string;
}

export interface DeletePersonalRecordRequest {
  userId: string;
  recordType: string;
}

/** Plugin Defaults */
export interface ListPluginDefaultsRequest {
  userId: string;
}

export interface ListPluginDefaultsResponse {
  defaults: { [key: string]: { [key: string]: any } | undefined };
}

export interface ListPluginDefaultsResponse_DefaultsEntry {
  key: string;
  value?: { [key: string]: any } | undefined;
}

export interface SetPluginDefaultsRequest {
  userId: string;
  pluginId: string;
  defaults?: { [key: string]: any } | undefined;
}

export interface DeletePluginDefaultsRequest {
  userId: string;
  pluginId: string;
}

/** Counter deletion */
export interface DeleteCounterRequest {
  userId: string;
  counterId: string;
}

export interface SetFCMTokenRequest {
  userId: string;
  token: string;
  /** "web", "android", "ios" */
  platform: string;
}

export interface UserService {
  CreateUser(request: CreateUserRequest): Promise<UserProfile>;
  GetProfile(request: GetProfileRequest): Promise<UserProfile>;
  ListUsers(request: ListUsersRequest): Promise<ListUsersResponse>;
  UpdateProfile(request: UpdateProfileRequest): Promise<UserProfile>;
  GetIntegration(request: GetIntegrationRequest): Promise<GetIntegrationResponse>;
  SetIntegration(request: SetIntegrationRequest): Promise<Empty>;
  DeleteIntegration(request: DeleteIntegrationRequest): Promise<Empty>;
  ListIntegrations(request: ListIntegrationsRequest): Promise<UserIntegrations>;
  GetNotificationPrefs(request: GetNotificationPrefsRequest): Promise<NotificationPreferences>;
  UpdateNotificationPrefs(request: UpdateNotificationPrefsRequest): Promise<NotificationPreferences>;
  ListCounters(request: ListCountersRequest): Promise<ListCountersResponse>;
  UpdateCounter(request: UpdateCounterRequest): Promise<Counter>;
  GetBoosterData(request: GetBoosterDataRequest): Promise<GetBoosterDataResponse>;
  SetBoosterData(request: SetBoosterDataRequest): Promise<Empty>;
  DeleteBoosterData(request: DeleteBoosterDataRequest): Promise<Empty>;
  DeleteUser(request: DeleteUserRequest): Promise<Empty>;
  /** Email Auth RPCs */
  SendVerificationEmail(request: SendVerificationEmailRequest): Promise<Empty>;
  SendPasswordResetEmail(request: SendPasswordResetEmailRequest): Promise<Empty>;
  SendEmailChangeVerification(request: SendEmailChangeVerificationRequest): Promise<Empty>;
  /** Administrative RPCs */
  GenerateRegistrationSummary(request: GenerateRegistrationSummaryRequest): Promise<Empty>;
  /** Integration Webhook Resolution */
  ResolveUserByIntegration(request: ResolveUserByIntegrationRequest): Promise<ResolveUserByIntegrationResponse>;
  /** Personal Records */
  ListPersonalRecords(request: ListPersonalRecordsRequest): Promise<ListPersonalRecordsResponse>;
  SetPersonalRecord(request: SetPersonalRecordRequest): Promise<PersonalRecord>;
  DeletePersonalRecord(request: DeletePersonalRecordRequest): Promise<Empty>;
  /** Plugin Defaults */
  ListPluginDefaults(request: ListPluginDefaultsRequest): Promise<ListPluginDefaultsResponse>;
  SetPluginDefaults(request: SetPluginDefaultsRequest): Promise<Empty>;
  DeletePluginDefaults(request: DeletePluginDefaultsRequest): Promise<Empty>;
  /** Counter deletion */
  DeleteCounter(request: DeleteCounterRequest): Promise<Empty>;
  /** FCM Token registration for push notifications */
  SetFCMToken(request: SetFCMTokenRequest): Promise<Empty>;
}
