/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get plugin registry
         * @description Returns all registered sources, enrichers, destinations, and integrations
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plugin registry */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PluginRegistryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a pending input */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["InputResolutionRequest"];
                };
            };
            responses: {
                /** @description Input resolved and activity re-published */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                /** @description Pending input not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inputs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Dismiss a pending input
         * @description Dismiss a pending input activity
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Input dismissed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Pending input not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inputs/fcm-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register FCM Token
         * @description Register a Firebase Cloud Messaging token for the user
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Token registered successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join waitlist */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        email: string;
                        websiteUrl?: string;
                    };
                };
            };
            responses: {
                /** @description Successfully joined */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Already on waitlist */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get activity stats */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Activity statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            synchronizedCount?: number;
                            totalSynced?: number;
                            monthlySynced?: number;
                            weeklySynced?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get activity details with execution trace
         * @description Returns activity details including pipelineExecution for trace visualization
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Activity Details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            activity?: components["schemas"]["SynchronizedActivity"];
                        };
                    };
                };
                /** @description Activity not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/unsynchronized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List unsynchronized pipeline executions
         * @description Lists pipeline executions that did not result in a synchronized activity
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of unsynchronized executions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            executions?: components["schemas"]["UnsynchronizedEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/unsynchronized/{pipelineExecutionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get unsynchronized pipeline execution trace */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pipelineExecutionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pipeline execution trace */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pipelineExecutionId?: string;
                            pipelineExecution?: components["schemas"]["ExecutionRecord"][];
                        };
                    };
                };
                /** @description Pipeline execution not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete user account
         * @description Permanently delete user account and all associated data (cascade delete)
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update user profile
         * @description Update allowed user profile fields
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Profile updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/users/me/counters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user counters
         * @description Returns all user-defined counters for dynamic select in Auto Increment enricher
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of counters */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Counter key/identifier */
                            id: string;
                            /** @description Current counter value */
                            count?: number;
                        }[];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/integrations/{provider}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate OAuth URL for provider
         * @description Generates an OAuth authorization URL for the specified provider
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "strava" | "fitbit";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OAuth URL generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OAuthConnectResponse"];
                    };
                };
                /** @description Invalid provider */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/integrations/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect integration
         * @description Removes the integration credentials for the specified provider
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "strava" | "fitbit" | "hevy";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Integration disconnected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Integration not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create pipeline
         * @description Creates a new pipeline for the user
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePipelineRequest"];
                };
            };
            responses: {
                /** @description Pipeline created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PipelineConfig"];
                    };
                };
                /** @description Invalid pipeline configuration */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/pipelines/{pipelineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete pipeline
         * @description Permanently removes a pipeline
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pipelineId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pipeline deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Pipeline not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update pipeline
         * @description Updates an existing pipeline configuration
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pipelineId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePipelineRequest"];
                };
            };
            responses: {
                /** @description Pipeline updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PipelineConfig"];
                    };
                };
                /** @description Invalid pipeline configuration */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Pipeline not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PendingInput: {
            id: string;
            activityId: string;
            userId?: string;
            /** @description 1=WAITING, 2=COMPLETED */
            status: number;
            requiredFields?: string[];
            inputData?: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt?: string;
            /** @description True if this pending input was auto-created by the system (e.g., for Parkrun results) */
            autoPopulated?: boolean;
            /** @description ID of the enricher that created this pending input (e.g., 'parkrun') */
            enricherProviderId?: string;
            /**
             * Format: date-time
             * @description Deadline for auto-resolution (after which user may need to provide manual input)
             */
            autoDeadline?: string;
            /** @description ID of the activity that was already created (for resume mode) */
            linkedActivityId?: string;
            /** @description ID of the pipeline that contains the enricher which created this pending input */
            pipelineId?: string;
            /** @description Provider-specific metadata for rich UI interactions (e.g., laps, presets) */
            providerMetadata?: {
                [key: string]: string;
            };
        };
        InputResolutionRequest: {
            activityId: string;
            inputData: {
                [key: string]: string;
            };
        };
        SynchronizedActivity: {
            activityId?: string;
            title?: string;
            description?: string;
            /** @description ActivityType enum */
            type?: number;
            source?: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            syncedAt?: string;
            pipelineId?: string;
            pipelineExecutionId?: string;
            pipelineExecution?: components["schemas"]["ExecutionRecord"][];
            destinations?: {
                [key: string]: string;
            };
        };
        ExecutionRecord: {
            executionId?: string;
            service?: string;
            status?: string;
            /** Format: date-time */
            timestamp?: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            errorMessage?: string;
            triggerType?: string;
            /** @description JSON-encoded input payload */
            inputsJson?: string;
            /** @description JSON-encoded output/result */
            outputsJson?: string;
        };
        UnsynchronizedEntry: {
            pipelineExecutionId?: string;
            title?: string;
            activityType?: string;
            source?: string;
            status?: string;
            errorMessage?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        UserProfile: {
            userId: string;
            /** Format: date-time */
            createdAt?: string;
            /**
             * @description User subscription tier
             * @enum {string}
             */
            tier?: "hobbyist" | "athlete";
            /** @description Whether user has admin privileges */
            isAdmin?: boolean;
            /**
             * Format: date-time
             * @description Trial expiration date, if applicable
             */
            trialEndsAt?: string;
            /** @description Number of syncs used this month */
            syncCountThisMonth?: number;
            integrations?: components["schemas"]["IntegrationsSummary"];
            pipelines?: components["schemas"]["PipelineConfig"][];
        };
        IntegrationsSummary: {
            hevy?: components["schemas"]["IntegrationStatus"];
            strava?: components["schemas"]["IntegrationStatus"];
            fitbit?: components["schemas"]["IntegrationStatus"];
            parkrun?: components["schemas"]["IntegrationStatus"];
        };
        IntegrationStatus: {
            connected: boolean;
            /** @description Masked or truncated external user ID */
            externalUserId?: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        PipelineConfig: {
            id: string;
            /** @description Optional user-friendly name for the pipeline */
            name?: string;
            source: string;
            enrichers?: components["schemas"]["EnricherConfig"][];
            destinations: string[];
        };
        EnricherConfig: {
            /** @description EnricherProviderType enum value */
            providerType: number;
            inputs?: {
                [key: string]: string;
            };
        };
        CreatePipelineRequest: {
            /** @description Optional user-friendly name for the pipeline */
            name?: string;
            source: string;
            enrichers?: components["schemas"]["EnricherConfig"][];
            destinations: string[];
        };
        UpdatePipelineRequest: {
            /** @description Optional user-friendly name for the pipeline */
            name?: string;
            source?: string;
            enrichers?: components["schemas"]["EnricherConfig"][];
            destinations?: string[];
        };
        OAuthConnectResponse: {
            /** @description OAuth authorization URL to redirect user to */
            authUrl: string;
        };
        ConfigFieldOption: {
            value: string;
            label: string;
        };
        ConfigFieldValidation: {
            minLength?: number;
            maxLength?: number;
            pattern?: string;
            minValue?: number;
            maxValue?: number;
        };
        ConfigFieldSchema: {
            key: string;
            label: string;
            description?: string;
            /** @description ConfigFieldType enum */
            fieldType: number;
            required?: boolean;
            defaultValue?: string;
            options?: components["schemas"]["ConfigFieldOption"][];
            validation?: components["schemas"]["ConfigFieldValidation"];
            dependsOn?: components["schemas"]["ConfigFieldDependency"];
            /** @description Options for the key side of KEY_VALUE_MAP */
            keyOptions?: components["schemas"]["ConfigFieldOption"][];
            /** @description Options for the value side of KEY_VALUE_MAP */
            valueOptions?: components["schemas"]["ConfigFieldOption"][];
            /** @description Key for dynamic data source (e.g., 'hevy_routines') */
            dynamicSource?: string;
        };
        ConfigFieldDependency: {
            /** @description Key of the field this depends on */
            fieldKey: string;
            /** @description Show when dependent field has one of these values */
            values: string[];
        };
        Transformation: {
            field?: string;
            label?: string;
            before?: string;
            after?: string;
            /** @description Visual rendering type (hr-graph, gps-map) - renders SVG instead of text when set */
            visualType?: string;
            /** @description Pre-formatted HTML for after state - used instead of after when set */
            afterHtml?: string;
        };
        PluginManifest: {
            id: string;
            /** @description PluginType enum */
            type: number;
            name: string;
            description?: string;
            icon?: string;
            enabled: boolean;
            requiredIntegrations?: string[];
            configSchema?: components["schemas"]["ConfigFieldSchema"][];
            enricherProviderType?: number;
            destinationType?: number;
            marketingDescription?: string;
            features?: string[];
            transformations?: components["schemas"]["Transformation"][];
            useCases?: string[];
            /** @description Template URL for external activity link (e.g., 'https://strava.com/activities/{id}') */
            externalUrlTemplate?: string;
            /** @description Required subscription tier to use this plugin (e.g., 'athlete') */
            requiredTier?: string;
            /** @description Category for UX grouping (e.g., 'wearables', 'stats', 'detection') */
            category?: string;
            /** @description Ordering within category (lower = first) */
            sortOrder?: number;
            /** @description Display premium badge (Athlete-tier) */
            isPremium?: boolean;
            /** @description Score for 'recommended' sorting in wizard */
            popularityScore?: number;
            /** @description Icon type: emoji, svg, png, or jpg */
            iconType?: string;
            /** @description Path to icon asset (e.g., /images/icons/strava.svg) */
            iconPath?: string;
            /** @description When true, this enricher can be added multiple times to a pipeline with different configs */
            allowMultipleInstances?: boolean;
        };
        IntegrationManifest: {
            id: string;
            name: string;
            description?: string;
            icon?: string;
            /** @description IntegrationAuthType enum */
            authType: number;
            enabled: boolean;
            docsUrl?: string;
            setupTitle?: string;
            setupInstructions?: string;
            apiKeyLabel?: string;
            apiKeyHelpUrl?: string;
            /** @description Icon type: emoji, svg, png, or jpg */
            iconType?: string;
            /** @description Path to icon asset (e.g., /images/icons/strava.svg) */
            iconPath?: string;
        };
        PluginRegistryResponse: {
            sources: components["schemas"]["PluginManifest"][];
            enrichers: components["schemas"]["PluginManifest"][];
            destinations: components["schemas"]["PluginManifest"][];
            integrations: components["schemas"]["IntegrationManifest"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
