/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ===================== Registry ===================== */
        get: operations["PublicGatewayService_GetPluginRegistry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicGatewayService_ListCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicGatewayService_ListPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry/plugins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicGatewayService_GetPlugin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicGatewayService_ListSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/showcase/profile/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicGatewayService_GetPublicShowcaseProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/showcase/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ===================== Public Showcase ===================== */
        get: operations["PublicGatewayService_GetPublicShowcase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConfigFieldDependency: {
            fieldKey?: string;
            values?: string[];
        };
        ConfigFieldOption: {
            value?: string;
            label?: string;
        };
        ConfigFieldSchema: {
            key?: string;
            label?: string;
            description?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            fieldType?: "CONFIG_FIELD_TYPE_UNSPECIFIED" | "CONFIG_FIELD_TYPE_STRING" | "CONFIG_FIELD_TYPE_NUMBER" | "CONFIG_FIELD_TYPE_BOOLEAN" | "CONFIG_FIELD_TYPE_SELECT" | "CONFIG_FIELD_TYPE_MULTI_SELECT" | "CONFIG_FIELD_TYPE_KEY_VALUE_MAP" | "CONFIG_FIELD_TYPE_DYNAMIC_SELECT";
            required?: boolean;
            defaultValue?: string;
            options?: components["schemas"]["ConfigFieldOption"][];
            validation?: components["schemas"]["ConfigFieldValidation"];
            dependsOn?: components["schemas"]["ConfigFieldDependency"];
            keyOptions?: components["schemas"]["ConfigFieldOption"][];
            valueOptions?: components["schemas"]["ConfigFieldOption"][];
            dynamicSource?: string;
            valueDynamicSource?: string;
        };
        ConfigFieldValidation: {
            /** Format: int32 */
            minLength?: number;
            /** Format: int32 */
            maxLength?: number;
            pattern?: string;
            /** Format: double */
            minValue?: number;
            /** Format: double */
            maxValue?: number;
        };
        GetPublicShowcaseProfileResponse: {
            profile?: components["schemas"]["ShowcaseProfile"];
            showcases?: components["schemas"]["ShowcasedActivity"][];
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
        };
        /** @description Contains an arbitrary serialized message along with a @type that describes the type of the serialized message. */
        GoogleProtobufAny: {
            /** @description The type of the serialized message. */
            "@type"?: string;
        } & {
            [key: string]: unknown;
        };
        IntegrationAction: {
            id?: string;
            label?: string;
            description?: string;
            icon?: string;
        };
        IntegrationManifest: {
            id?: string;
            name?: string;
            description?: string;
            icon?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            authType?: "INTEGRATION_AUTH_TYPE_UNSPECIFIED" | "INTEGRATION_AUTH_TYPE_OAUTH" | "INTEGRATION_AUTH_TYPE_API_KEY" | "INTEGRATION_AUTH_TYPE_APP_SYNC" | "INTEGRATION_AUTH_TYPE_PUBLIC_ID";
            enabled?: boolean;
            docsUrl?: string;
            setupTitle?: string;
            setupInstructions?: string;
            apiKeyLabel?: string;
            apiKeyHelpUrl?: string;
            marketingDescription?: string;
            features?: string[];
            iconType?: string;
            iconPath?: string;
            isTemporarilyUnavailable?: boolean;
            actions?: components["schemas"]["IntegrationAction"][];
        };
        Lap: {
            /** Format: date-time */
            startTime?: string;
            /** Format: double */
            totalElapsedTime?: number;
            /** Format: double */
            totalDistance?: number;
            records?: components["schemas"]["Record"][];
            exerciseName?: string;
            intensity?: string;
        };
        ListCategoriesPublicResponse: {
            categories?: string[];
        };
        ListPluginsPublicResponse: {
            plugins?: components["schemas"]["PluginManifest"][];
        };
        ListSourcesPublicResponse: {
            sources?: components["schemas"]["PluginManifest"][];
        };
        PluginManifest: {
            id?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            type?: "PLUGIN_TYPE_UNSPECIFIED" | "PLUGIN_TYPE_SOURCE" | "PLUGIN_TYPE_ENRICHER" | "PLUGIN_TYPE_DESTINATION";
            name?: string;
            description?: string;
            icon?: string;
            configSchema?: components["schemas"]["ConfigFieldSchema"][];
            requiredIntegrations?: string[];
            enabled?: boolean;
            /** Format: int32 */
            enricherProviderType?: number;
            /** Format: int32 */
            destinationType?: number;
            marketingDescription?: string;
            features?: string[];
            transformations?: components["schemas"]["Transformation"][];
            useCases?: string[];
            externalUrlTemplate?: string;
            requiredTier?: string;
            category?: string;
            /** Format: int32 */
            sortOrder?: number;
            isPremium?: boolean;
            /** Format: int32 */
            popularityScore?: number;
            iconType?: string;
            iconPath?: string;
            isTemporarilyUnavailable?: boolean;
            allowMultipleInstances?: boolean;
        };
        PluginRegistryResponse: {
            sources?: components["schemas"]["PluginManifest"][];
            enrichers?: components["schemas"]["PluginManifest"][];
            destinations?: components["schemas"]["PluginManifest"][];
            integrations?: components["schemas"]["IntegrationManifest"][];
        };
        Record: {
            /** Format: date-time */
            timestamp?: string;
            /** Format: int32 */
            heartRate?: number;
            /** Format: int32 */
            power?: number;
            /** Format: int32 */
            cadence?: number;
            /** Format: double */
            speed?: number;
            /** Format: double */
            altitude?: number;
            /** Format: double */
            positionLat?: number;
            /** Format: double */
            positionLong?: number;
            /** Format: int32 */
            groundContactTime?: number;
            /** Format: int32 */
            verticalOscillation?: number;
            /** Format: int32 */
            verticalRatio?: number;
            /** Format: double */
            stepLength?: number;
        };
        Session: {
            /** Format: date-time */
            startTime?: string;
            /** Format: double */
            totalElapsedTime?: number;
            /** Format: double */
            totalDistance?: number;
            laps?: components["schemas"]["Lap"][];
            strengthSets?: components["schemas"]["StrengthSet"][];
            /** Format: double */
            totalCalories?: number;
            /** Format: int32 */
            avgHeartRate?: number;
            /** Format: int32 */
            maxHeartRate?: number;
        };
        ShowcaseProfile: {
            slug?: string;
            userId?: string;
            displayName?: string;
            entries?: components["schemas"]["ShowcaseProfileEntry"][];
            /** Format: int32 */
            totalActivities?: number;
            /** Format: double */
            totalDistanceMeters?: number;
            /** Format: double */
            totalDurationSeconds?: number;
            /** Format: date-time */
            latestActivityAt?: string;
            /** Format: int32 */
            totalSets?: number;
            /** Format: int32 */
            totalReps?: number;
            /** Format: double */
            totalWeightKg?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            subtitle?: string;
            bio?: string;
            profilePictureUrl?: string;
            visible?: boolean;
            theme?: components["schemas"]["ShowcaseTheme"];
        };
        ShowcaseProfileEntry: {
            showcaseId?: string;
            title?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            activityType?: "ACTIVITY_TYPE_UNSPECIFIED" | "ACTIVITY_TYPE_ALPINE_SKI" | "ACTIVITY_TYPE_BACKCOUNTRY_SKI" | "ACTIVITY_TYPE_BADMINTON" | "ACTIVITY_TYPE_CANOEING" | "ACTIVITY_TYPE_CROSSFIT" | "ACTIVITY_TYPE_EBIKE_RIDE" | "ACTIVITY_TYPE_ELLIPTICAL" | "ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE" | "ACTIVITY_TYPE_GOLF" | "ACTIVITY_TYPE_GRAVEL_RIDE" | "ACTIVITY_TYPE_HANDCYCLE" | "ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING" | "ACTIVITY_TYPE_HIKE" | "ACTIVITY_TYPE_ICE_SKATE" | "ACTIVITY_TYPE_INLINE_SKATE" | "ACTIVITY_TYPE_KAYAKING" | "ACTIVITY_TYPE_KITESURF" | "ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE" | "ACTIVITY_TYPE_NORDIC_SKI" | "ACTIVITY_TYPE_PICKLEBALL" | "ACTIVITY_TYPE_PILATES" | "ACTIVITY_TYPE_RACQUETBALL" | "ACTIVITY_TYPE_RIDE" | "ACTIVITY_TYPE_ROCK_CLIMBING" | "ACTIVITY_TYPE_ROLLER_SKI" | "ACTIVITY_TYPE_ROWING" | "ACTIVITY_TYPE_RUN" | "ACTIVITY_TYPE_SAIL" | "ACTIVITY_TYPE_SKATEBOARD" | "ACTIVITY_TYPE_SNOWBOARD" | "ACTIVITY_TYPE_SNOWSHOE" | "ACTIVITY_TYPE_SOCCER" | "ACTIVITY_TYPE_SQUASH" | "ACTIVITY_TYPE_STAIR_STEPPER" | "ACTIVITY_TYPE_STAND_UP_PADDLING" | "ACTIVITY_TYPE_SURFING" | "ACTIVITY_TYPE_SWIM" | "ACTIVITY_TYPE_TABLE_TENNIS" | "ACTIVITY_TYPE_TENNIS" | "ACTIVITY_TYPE_TRAIL_RUN" | "ACTIVITY_TYPE_VELOMOBILE" | "ACTIVITY_TYPE_VIRTUAL_RIDE" | "ACTIVITY_TYPE_VIRTUAL_ROW" | "ACTIVITY_TYPE_VIRTUAL_RUN" | "ACTIVITY_TYPE_WALK" | "ACTIVITY_TYPE_WEIGHT_TRAINING" | "ACTIVITY_TYPE_WHEELCHAIR" | "ACTIVITY_TYPE_WINDSURF" | "ACTIVITY_TYPE_WORKOUT" | "ACTIVITY_TYPE_YOGA";
            /**
             * Format: enum
             * @enum {string}
             */
            source?: "SOURCE_UNSPECIFIED" | "SOURCE_HEVY" | "SOURCE_FITBIT" | "SOURCE_PARKRUN_RESULTS" | "SOURCE_FILE_UPLOAD" | "SOURCE_STRAVA" | "SOURCE_GARMIN" | "SOURCE_APPLE_HEALTH" | "SOURCE_HEALTH_CONNECT" | "SOURCE_OURA" | "SOURCE_POLAR" | "SOURCE_WAHOO" | "SOURCE_INTERVALS" | "SOURCE_TRAININGPEAKS" | "SOURCE_GOOGLESHEETS" | "SOURCE_GITHUB" | "SOURCE_TEST";
            /** Format: date-time */
            startTime?: string;
            routeThumbnailUrl?: string;
            /** Format: double */
            distanceMeters?: number;
            /** Format: double */
            durationSeconds?: number;
            /** Format: int32 */
            totalSets?: number;
            /** Format: int32 */
            totalReps?: number;
            /** Format: double */
            totalWeightKg?: number;
        };
        ShowcaseTheme: {
            themeId?: string;
            customAccentColor?: string;
            animationId?: string;
            cardStyle?: string;
        };
        /** @description ShowcasedActivity represents a publicly shareable activity snapshot. */
        ShowcasedActivity: {
            showcaseId?: string;
            activityId?: string;
            userId?: string;
            title?: string;
            description?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            activityType?: "ACTIVITY_TYPE_UNSPECIFIED" | "ACTIVITY_TYPE_ALPINE_SKI" | "ACTIVITY_TYPE_BACKCOUNTRY_SKI" | "ACTIVITY_TYPE_BADMINTON" | "ACTIVITY_TYPE_CANOEING" | "ACTIVITY_TYPE_CROSSFIT" | "ACTIVITY_TYPE_EBIKE_RIDE" | "ACTIVITY_TYPE_ELLIPTICAL" | "ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE" | "ACTIVITY_TYPE_GOLF" | "ACTIVITY_TYPE_GRAVEL_RIDE" | "ACTIVITY_TYPE_HANDCYCLE" | "ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING" | "ACTIVITY_TYPE_HIKE" | "ACTIVITY_TYPE_ICE_SKATE" | "ACTIVITY_TYPE_INLINE_SKATE" | "ACTIVITY_TYPE_KAYAKING" | "ACTIVITY_TYPE_KITESURF" | "ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE" | "ACTIVITY_TYPE_NORDIC_SKI" | "ACTIVITY_TYPE_PICKLEBALL" | "ACTIVITY_TYPE_PILATES" | "ACTIVITY_TYPE_RACQUETBALL" | "ACTIVITY_TYPE_RIDE" | "ACTIVITY_TYPE_ROCK_CLIMBING" | "ACTIVITY_TYPE_ROLLER_SKI" | "ACTIVITY_TYPE_ROWING" | "ACTIVITY_TYPE_RUN" | "ACTIVITY_TYPE_SAIL" | "ACTIVITY_TYPE_SKATEBOARD" | "ACTIVITY_TYPE_SNOWBOARD" | "ACTIVITY_TYPE_SNOWSHOE" | "ACTIVITY_TYPE_SOCCER" | "ACTIVITY_TYPE_SQUASH" | "ACTIVITY_TYPE_STAIR_STEPPER" | "ACTIVITY_TYPE_STAND_UP_PADDLING" | "ACTIVITY_TYPE_SURFING" | "ACTIVITY_TYPE_SWIM" | "ACTIVITY_TYPE_TABLE_TENNIS" | "ACTIVITY_TYPE_TENNIS" | "ACTIVITY_TYPE_TRAIL_RUN" | "ACTIVITY_TYPE_VELOMOBILE" | "ACTIVITY_TYPE_VIRTUAL_RIDE" | "ACTIVITY_TYPE_VIRTUAL_ROW" | "ACTIVITY_TYPE_VIRTUAL_RUN" | "ACTIVITY_TYPE_WALK" | "ACTIVITY_TYPE_WEIGHT_TRAINING" | "ACTIVITY_TYPE_WHEELCHAIR" | "ACTIVITY_TYPE_WINDSURF" | "ACTIVITY_TYPE_WORKOUT" | "ACTIVITY_TYPE_YOGA";
            /**
             * Format: enum
             * @enum {string}
             */
            source?: "SOURCE_UNSPECIFIED" | "SOURCE_HEVY" | "SOURCE_FITBIT" | "SOURCE_PARKRUN_RESULTS" | "SOURCE_FILE_UPLOAD" | "SOURCE_STRAVA" | "SOURCE_GARMIN" | "SOURCE_APPLE_HEALTH" | "SOURCE_HEALTH_CONNECT" | "SOURCE_OURA" | "SOURCE_POLAR" | "SOURCE_WAHOO" | "SOURCE_INTERVALS" | "SOURCE_TRAININGPEAKS" | "SOURCE_GOOGLESHEETS" | "SOURCE_GITHUB" | "SOURCE_TEST";
            /** Format: date-time */
            startTime?: string;
            activityData?: components["schemas"]["StandardizedActivity"];
            fitFileUri?: string;
            appliedEnrichments?: string[];
            enrichmentMetadata?: {
                [key: string]: string;
            };
            tags?: string[];
            pipelineExecutionId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            ownerDisplayName?: string;
            activityDataUri?: string;
        };
        StandardizedActivity: {
            /**
             * Format: enum
             * @enum {string}
             */
            source?: "SOURCE_UNSPECIFIED" | "SOURCE_HEVY" | "SOURCE_FITBIT" | "SOURCE_PARKRUN_RESULTS" | "SOURCE_FILE_UPLOAD" | "SOURCE_STRAVA" | "SOURCE_GARMIN" | "SOURCE_APPLE_HEALTH" | "SOURCE_HEALTH_CONNECT" | "SOURCE_OURA" | "SOURCE_POLAR" | "SOURCE_WAHOO" | "SOURCE_INTERVALS" | "SOURCE_TRAININGPEAKS" | "SOURCE_GOOGLESHEETS" | "SOURCE_GITHUB" | "SOURCE_TEST";
            externalId?: string;
            userId?: string;
            /** Format: date-time */
            startTime?: string;
            name?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            type?: "ACTIVITY_TYPE_UNSPECIFIED" | "ACTIVITY_TYPE_ALPINE_SKI" | "ACTIVITY_TYPE_BACKCOUNTRY_SKI" | "ACTIVITY_TYPE_BADMINTON" | "ACTIVITY_TYPE_CANOEING" | "ACTIVITY_TYPE_CROSSFIT" | "ACTIVITY_TYPE_EBIKE_RIDE" | "ACTIVITY_TYPE_ELLIPTICAL" | "ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE" | "ACTIVITY_TYPE_GOLF" | "ACTIVITY_TYPE_GRAVEL_RIDE" | "ACTIVITY_TYPE_HANDCYCLE" | "ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING" | "ACTIVITY_TYPE_HIKE" | "ACTIVITY_TYPE_ICE_SKATE" | "ACTIVITY_TYPE_INLINE_SKATE" | "ACTIVITY_TYPE_KAYAKING" | "ACTIVITY_TYPE_KITESURF" | "ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE" | "ACTIVITY_TYPE_NORDIC_SKI" | "ACTIVITY_TYPE_PICKLEBALL" | "ACTIVITY_TYPE_PILATES" | "ACTIVITY_TYPE_RACQUETBALL" | "ACTIVITY_TYPE_RIDE" | "ACTIVITY_TYPE_ROCK_CLIMBING" | "ACTIVITY_TYPE_ROLLER_SKI" | "ACTIVITY_TYPE_ROWING" | "ACTIVITY_TYPE_RUN" | "ACTIVITY_TYPE_SAIL" | "ACTIVITY_TYPE_SKATEBOARD" | "ACTIVITY_TYPE_SNOWBOARD" | "ACTIVITY_TYPE_SNOWSHOE" | "ACTIVITY_TYPE_SOCCER" | "ACTIVITY_TYPE_SQUASH" | "ACTIVITY_TYPE_STAIR_STEPPER" | "ACTIVITY_TYPE_STAND_UP_PADDLING" | "ACTIVITY_TYPE_SURFING" | "ACTIVITY_TYPE_SWIM" | "ACTIVITY_TYPE_TABLE_TENNIS" | "ACTIVITY_TYPE_TENNIS" | "ACTIVITY_TYPE_TRAIL_RUN" | "ACTIVITY_TYPE_VELOMOBILE" | "ACTIVITY_TYPE_VIRTUAL_RIDE" | "ACTIVITY_TYPE_VIRTUAL_ROW" | "ACTIVITY_TYPE_VIRTUAL_RUN" | "ACTIVITY_TYPE_WALK" | "ACTIVITY_TYPE_WEIGHT_TRAINING" | "ACTIVITY_TYPE_WHEELCHAIR" | "ACTIVITY_TYPE_WINDSURF" | "ACTIVITY_TYPE_WORKOUT" | "ACTIVITY_TYPE_YOGA";
            sessions?: components["schemas"]["Session"][];
            description?: string;
            tags?: string[];
            notes?: string;
            timeMarkers?: components["schemas"]["TimeMarker"][];
            workout?: components["schemas"]["WorkoutDefinition"];
        };
        /** @description The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors). */
        Status: {
            /**
             * Format: int32
             * @description The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
             */
            code?: number;
            /** @description A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client. */
            message?: string;
            /** @description A list of messages that carry the error details.  There is a common set of message types for APIs to use. */
            details?: components["schemas"]["GoogleProtobufAny"][];
        };
        StrengthSet: {
            exerciseName?: string;
            /** Format: int32 */
            reps?: number;
            /** Format: double */
            weightKg?: number;
            /** Format: date-time */
            startTime?: string;
            /** Format: int32 */
            durationSeconds?: number;
            notes?: string;
            supersetId?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            primaryMuscleGroup?: "MUSCLE_GROUP_UNSPECIFIED" | "MUSCLE_GROUP_ABDOMINALS" | "MUSCLE_GROUP_SHOULDERS" | "MUSCLE_GROUP_BICEPS" | "MUSCLE_GROUP_TRICEPS" | "MUSCLE_GROUP_FOREARMS" | "MUSCLE_GROUP_QUADRICEPS" | "MUSCLE_GROUP_HAMSTRINGS" | "MUSCLE_GROUP_CALVES" | "MUSCLE_GROUP_GLUTES" | "MUSCLE_GROUP_ABDUCTORS" | "MUSCLE_GROUP_ADDUCTORS" | "MUSCLE_GROUP_LATS" | "MUSCLE_GROUP_UPPER_BACK" | "MUSCLE_GROUP_TRAPS" | "MUSCLE_GROUP_LOWER_BACK" | "MUSCLE_GROUP_CHEST" | "MUSCLE_GROUP_CARDIO" | "MUSCLE_GROUP_NECK" | "MUSCLE_GROUP_FULL_BODY" | "MUSCLE_GROUP_OTHER";
            secondaryMuscleGroups?: ("MUSCLE_GROUP_UNSPECIFIED" | "MUSCLE_GROUP_ABDOMINALS" | "MUSCLE_GROUP_SHOULDERS" | "MUSCLE_GROUP_BICEPS" | "MUSCLE_GROUP_TRICEPS" | "MUSCLE_GROUP_FOREARMS" | "MUSCLE_GROUP_QUADRICEPS" | "MUSCLE_GROUP_HAMSTRINGS" | "MUSCLE_GROUP_CALVES" | "MUSCLE_GROUP_GLUTES" | "MUSCLE_GROUP_ABDUCTORS" | "MUSCLE_GROUP_ADDUCTORS" | "MUSCLE_GROUP_LATS" | "MUSCLE_GROUP_UPPER_BACK" | "MUSCLE_GROUP_TRAPS" | "MUSCLE_GROUP_LOWER_BACK" | "MUSCLE_GROUP_CHEST" | "MUSCLE_GROUP_CARDIO" | "MUSCLE_GROUP_NECK" | "MUSCLE_GROUP_FULL_BODY" | "MUSCLE_GROUP_OTHER")[];
            /** Format: double */
            distanceMeters?: number;
            setType?: string;
        };
        TimeMarker: {
            /** Format: date-time */
            timestamp?: string;
            label?: string;
            markerType?: string;
        };
        Transformation: {
            field?: string;
            label?: string;
            before?: string;
            after?: string;
            visualType?: string;
            afterHtml?: string;
        };
        WorkoutDefinition: {
            name?: string;
            steps?: components["schemas"]["WorkoutStep"][];
        };
        WorkoutStep: {
            intensity?: string;
            durationType?: string;
            /** Format: uint32 */
            durationValue?: number;
            targetType?: string;
            /** Format: uint32 */
            targetLow?: number;
            /** Format: uint32 */
            targetHigh?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PublicGatewayService_GetPluginRegistry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginRegistryResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PublicGatewayService_ListCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCategoriesPublicResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PublicGatewayService_ListPlugins: {
        parameters: {
            query?: {
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPluginsPublicResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PublicGatewayService_GetPlugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginManifest"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PublicGatewayService_ListSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSourcesPublicResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PublicGatewayService_GetPublicShowcaseProfile: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPublicShowcaseProfileResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    PublicGatewayService_GetPublicShowcase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowcasedActivity"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
}
