/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ===================== Audit Log ===================== */
        get: operations["AdminGatewayService_ListAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminGatewayService_ListPipelineRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ===================== Pipeline Management ===================== */
        get: operations["AdminGatewayService_ListAllPipelines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ===================== Platform Stats ===================== */
        get: operations["AdminGatewayService_GetStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ===================== User Management ===================== */
        get: operations["AdminGatewayService_ListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminGatewayService_GetUser"];
        put: operations["AdminGatewayService_UpdateUser"];
        post?: never;
        delete: operations["AdminGatewayService_DeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/activities/{activityId}/repost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminGatewayService_RepostActivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ===================== Billing ===================== */
        get: operations["AdminGatewayService_GetUserBilling"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/billing/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminGatewayService_CancelSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminGatewayService_CreateBillingPortalSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/billing/trial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminGatewayService_StartTrial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/integrations/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminGatewayService_DeleteIntegration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/integrations/{provider}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminGatewayService_SetIntegrationEnabled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/pending-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminGatewayService_ListPendingInputs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/pending-inputs/{inputId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminGatewayService_ResolvePendingInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/pipeline-runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminGatewayService_GetPipelineRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/pipeline-runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminGatewayService_CancelPipelineRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/pipelines/{pipelineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminGatewayService_GetPipeline"];
        put: operations["AdminGatewayService_UpdatePipeline"];
        post?: never;
        delete: operations["AdminGatewayService_DeletePipeline"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/send-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ===================== User Actions ===================== */
        post: operations["AdminGatewayService_SendPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/send-verification-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminGatewayService_SendVerificationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/{dataType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminGatewayService_DeleteUserData"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description ----------------------- Audit Log ----------------------- */
        AdminAuditLogEntry: {
            id?: string;
            actorUid?: string;
            actorEmail?: string;
            action?: string;
            targetUserId?: string;
            params?: {
                [key: string]: string;
            };
            result?: string;
            error?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        AdminEmptyResponse: Record<string, never>;
        /**
         * @description AdminIntegrationSummary is a redacted view of a connected provider — it never
         *      includes tokens or secrets, only status/health metadata.
         */
        AdminIntegrationSummary: {
            provider?: string;
            enabled?: boolean;
            connected?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @description "valid" | "expired" | "n/a" (n/a = provider has no expiring token) */
            tokenHealth?: string;
        };
        AdminPendingInputSummary: {
            id?: string;
            activityId?: string;
            enricherProviderId?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        AdminPipelineRunStats: {
            /** Format: int32 */
            total?: number;
            byStatus?: {
                [key: string]: number;
            };
            bySource?: {
                [key: string]: number;
            };
        };
        AdminPipelineSummary: {
            id?: string;
            name?: string;
            source?: string;
            destinations?: string[];
            enabled?: boolean;
        };
        AdminUserBilling: {
            subscription?: components["schemas"]["SubscriptionState"];
            /**
             * Format: enum
             * @enum {string}
             */
            effectiveTier?: "USER_TIER_UNSPECIFIED" | "USER_TIER_HOBBYIST" | "USER_TIER_ATHLETE";
            isTrial?: boolean;
        };
        /** @description AdminUserDetail is the aggregated 360-degree view of a single user. */
        AdminUserDetail: {
            profile?: components["schemas"]["UserProfile"];
            integrations?: components["schemas"]["AdminIntegrationSummary"][];
            pipelines?: components["schemas"]["AdminPipelineSummary"][];
            /** Format: int32 */
            activityCount?: number;
            /** Format: int32 */
            pipelineRunCount?: number;
            pendingInputs?: components["schemas"]["AdminPendingInputSummary"][];
            billing?: components["schemas"]["AdminUserBilling"];
        };
        /**
         * @description AdminUserSummary is the per-row shape for the user directory. It carries the
         *      derived counts the table needs without the client having to aggregate.
         */
        AdminUserSummary: {
            userId?: string;
            email?: string;
            displayName?: string;
            /** Format: date-time */
            createdAt?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            tier?: "USER_TIER_UNSPECIFIED" | "USER_TIER_HOBBYIST" | "USER_TIER_ATHLETE";
            isAdmin?: boolean;
            accessEnabled?: boolean;
            /** Format: int32 */
            syncCountThisMonth?: number;
            /** Format: int32 */
            preventedSyncCount?: number;
            /** Format: int32 */
            integrationCount?: number;
            /** Format: int32 */
            pipelineCount?: number;
            /** Format: date-time */
            trialEndsAt?: string;
            stripeCustomerId?: string;
            integrations?: string[];
        };
        BoosterExecution: {
            providerName?: string;
            durationMs?: string;
            metadata?: {
                [key: string]: string;
            };
            error?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "EXECUTION_STEP_STATUS_UNSPECIFIED" | "EXECUTION_STEP_STATUS_QUEUED" | "EXECUTION_STEP_STATUS_RUNNING" | "EXECUTION_STEP_STATUS_OK" | "EXECUTION_STEP_STATUS_PASS" | "EXECUTION_STEP_STATUS_SKIPPED" | "EXECUTION_STEP_STATUS_FAILED" | "EXECUTION_STEP_STATUS_RETRIED";
        };
        CancelPipelineRunAdminRequest: {
            id?: string;
            runId?: string;
        };
        /** @description ----------------------- Billing ----------------------- */
        CreateBillingPortalAdminRequest: {
            id?: string;
            returnUrl?: string;
        };
        CreateBillingPortalAdminResponse: {
            url?: string;
        };
        DestinationConfig: {
            config?: {
                [key: string]: string;
            };
            excludedEnrichers?: string[];
        };
        DestinationOutcome: {
            /**
             * Format: enum
             * @enum {string}
             */
            destination?: "DESTINATION_UNSPECIFIED" | "DESTINATION_STRAVA" | "DESTINATION_SHOWCASE" | "DESTINATION_HEVY" | "DESTINATION_TRAININGPEAKS" | "DESTINATION_INTERVALS" | "DESTINATION_GOOGLESHEETS" | "DESTINATION_GITHUB" | "DESTINATION_MOCK";
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "DESTINATION_STATUS_UNSPECIFIED" | "DESTINATION_STATUS_PENDING" | "DESTINATION_STATUS_SUCCESS" | "DESTINATION_STATUS_FAILED" | "DESTINATION_STATUS_SKIPPED";
            externalId?: string;
            error?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        EnricherConfig: {
            /**
             * Format: enum
             * @enum {string}
             */
            providerType?: "ENRICHER_PROVIDER_UNSPECIFIED" | "ENRICHER_PROVIDER_FITBIT_HEART_RATE" | "ENRICHER_PROVIDER_WORKOUT_SUMMARY" | "ENRICHER_PROVIDER_MUSCLE_HEATMAP" | "ENRICHER_PROVIDER_SOURCE_LINK" | "ENRICHER_PROVIDER_VIRTUAL_GPS" | "ENRICHER_PROVIDER_TYPE_MAPPER" | "ENRICHER_PROVIDER_PARKRUN" | "ENRICHER_PROVIDER_CONDITION_MATCHER" | "ENRICHER_PROVIDER_AUTO_INCREMENT" | "ENRICHER_PROVIDER_USER_INPUT" | "ENRICHER_PROVIDER_ACTIVITY_FILTER" | "ENRICHER_PROVIDER_LOGIC_GATE" | "ENRICHER_PROVIDER_HEART_RATE_SUMMARY" | "ENRICHER_PROVIDER_AI_COMPANION" | "ENRICHER_PROVIDER_PACE_SUMMARY" | "ENRICHER_PROVIDER_CADENCE_SUMMARY" | "ENRICHER_PROVIDER_POWER_SUMMARY" | "ENRICHER_PROVIDER_SPEED_SUMMARY" | "ENRICHER_PROVIDER_PERSONAL_RECORDS" | "ENRICHER_PROVIDER_TRAINING_LOAD" | "ENRICHER_PROVIDER_SPOTIFY_TRACKS" | "ENRICHER_PROVIDER_WEATHER" | "ENRICHER_PROVIDER_ELEVATION_SUMMARY" | "ENRICHER_PROVIDER_LOCATION_NAMING" | "ENRICHER_PROVIDER_MUSCLE_HEATMAP_IMAGE" | "ENRICHER_PROVIDER_ROUTE_THUMBNAIL" | "ENRICHER_PROVIDER_AI_BANNER" | "ENRICHER_PROVIDER_FIT_FILE_HEART_RATE" | "ENRICHER_PROVIDER_HYBRID_RACE_TAGGER" | "ENRICHER_PROVIDER_RUNNING_DYNAMICS" | "ENRICHER_PROVIDER_HEART_RATE_ZONES" | "ENRICHER_PROVIDER_CALORIES_BURNED" | "ENRICHER_PROVIDER_GOAL_TRACKER" | "ENRICHER_PROVIDER_STREAK_TRACKER" | "ENRICHER_PROVIDER_DISTANCE_MILESTONES" | "ENRICHER_PROVIDER_RECOVERY_ADVISOR" | "ENRICHER_PROVIDER_EFFORT_SCORE" | "ENRICHER_PROVIDER_INTERVALS" | "ENRICHER_PROVIDER_PHOTO_UPLOAD" | "ENRICHER_PROVIDER_MANUAL_WORKOUT_ENTRY" | "ENRICHER_PROVIDER_AI_ACTIVITY_TYPE" | "ENRICHER_PROVIDER_ICAL_TITLE" | "ENRICHER_PROVIDER_TEMPERATURE_SUMMARY" | "ENRICHER_PROVIDER_BEST_EFFORTS" | "ENRICHER_PROVIDER_HDROP" | "ENRICHER_PROVIDER_LOCATION_PINNER" | "ENRICHER_PROVIDER_MOCK";
            typedConfig?: {
                [key: string]: string;
            };
            nonBlocking?: boolean;
        };
        /** @description ExecutionStep is the unified record for a single step in a pipeline run. */
        ExecutionStep: {
            id?: string;
            /** Format: int32 */
            ordinal?: number;
            /**
             * Format: enum
             * @enum {string}
             */
            kind?: "EXECUTION_STEP_KIND_UNSPECIFIED" | "EXECUTION_STEP_KIND_SOURCE" | "EXECUTION_STEP_KIND_PARSE" | "EXECUTION_STEP_KIND_GATE" | "EXECUTION_STEP_KIND_ENRICHER_BATCH" | "EXECUTION_STEP_KIND_ROUTER" | "EXECUTION_STEP_KIND_DESTINATION";
            displayName?: string;
            service?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "EXECUTION_STEP_STATUS_UNSPECIFIED" | "EXECUTION_STEP_STATUS_QUEUED" | "EXECUTION_STEP_STATUS_RUNNING" | "EXECUTION_STEP_STATUS_OK" | "EXECUTION_STEP_STATUS_PASS" | "EXECUTION_STEP_STATUS_SKIPPED" | "EXECUTION_STEP_STATUS_FAILED" | "EXECUTION_STEP_STATUS_RETRIED";
            offsetMs?: string;
            durationMs?: string;
            statusLabel?: string;
            error?: string;
            metadata?: {
                [key: string]: string;
            };
        };
        GetAdminStatsResponse: {
            /** Format: int32 */
            totalUsers?: number;
            /** Format: int32 */
            athleteUsers?: number;
            /** Format: int32 */
            adminUsers?: number;
            /** Format: int32 */
            totalSyncsThisMonth?: number;
            recentExecutions?: components["schemas"]["RecentPipelineRunCounts"];
        };
        /** @description Contains an arbitrary serialized message along with a @type that describes the type of the serialized message. */
        GoogleProtobufAny: {
            /** @description The type of the serialized message. */
            "@type"?: string;
        } & {
            [key: string]: unknown;
        };
        ListAllPipelinesAdminResponse: {
            pipelines?: components["schemas"]["PipelineConfig"][];
        };
        ListAuditLogAdminResponse: {
            entries?: components["schemas"]["AdminAuditLogEntry"][];
            nextPageToken?: string;
        };
        ListPendingInputsAdminResponse: {
            inputs?: components["schemas"]["AdminPendingInputSummary"][];
        };
        ListPipelineRunsAdminResponse: {
            runs?: components["schemas"]["PipelineRun"][];
            nextPageToken?: string;
            hasMore?: boolean;
            stats?: components["schemas"]["AdminPipelineRunStats"];
        };
        ListUsersAdminResponse: {
            users?: components["schemas"]["AdminUserSummary"][];
            nextPageToken?: string;
        };
        NotificationPreferences: {
            pendingInput?: components["schemas"]["NotificationTypePreference"];
            pipelineSuccess?: components["schemas"]["NotificationTypePreference"];
            pipelineFailure?: components["schemas"]["NotificationTypePreference"];
            connectionAction?: components["schemas"]["NotificationTypePreference"];
            showcaseRoundup?: components["schemas"]["NotificationTypePreference"];
            pipelineCancelled?: components["schemas"]["NotificationTypePreference"];
        };
        /**
         * @description NotificationTypePreference holds which channels are active for one notification type.
         *      An empty channels list means the notification type is disabled entirely.
         *      A nil/absent preference means "use the default" which is [PUSH].
         */
        NotificationTypePreference: {
            channels?: ("NOTIFICATION_CHANNEL_UNSPECIFIED" | "NOTIFICATION_CHANNEL_PUSH" | "NOTIFICATION_CHANNEL_EMAIL")[];
        };
        PipelineConfig: {
            id?: string;
            source?: string;
            enrichers?: components["schemas"]["EnricherConfig"][];
            destinations?: ("DESTINATION_UNSPECIFIED" | "DESTINATION_STRAVA" | "DESTINATION_SHOWCASE" | "DESTINATION_HEVY" | "DESTINATION_TRAININGPEAKS" | "DESTINATION_INTERVALS" | "DESTINATION_GOOGLESHEETS" | "DESTINATION_GITHUB" | "DESTINATION_MOCK")[];
            name?: string;
            disabled?: boolean;
            sourceConfig?: {
                [key: string]: string;
            };
            destinationConfigs?: {
                [key: string]: components["schemas"]["DestinationConfig"];
            };
            sources?: string[];
        };
        PipelineRun: {
            id?: string;
            pipelineId?: string;
            activityId?: string;
            source?: string;
            sourceActivityId?: string;
            title?: string;
            description?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            type?: "ACTIVITY_TYPE_UNSPECIFIED" | "ACTIVITY_TYPE_ALPINE_SKI" | "ACTIVITY_TYPE_BACKCOUNTRY_SKI" | "ACTIVITY_TYPE_BADMINTON" | "ACTIVITY_TYPE_CANOEING" | "ACTIVITY_TYPE_CROSSFIT" | "ACTIVITY_TYPE_EBIKE_RIDE" | "ACTIVITY_TYPE_ELLIPTICAL" | "ACTIVITY_TYPE_EMOUNTAIN_BIKE_RIDE" | "ACTIVITY_TYPE_GOLF" | "ACTIVITY_TYPE_GRAVEL_RIDE" | "ACTIVITY_TYPE_HANDCYCLE" | "ACTIVITY_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING" | "ACTIVITY_TYPE_HIKE" | "ACTIVITY_TYPE_ICE_SKATE" | "ACTIVITY_TYPE_INLINE_SKATE" | "ACTIVITY_TYPE_KAYAKING" | "ACTIVITY_TYPE_KITESURF" | "ACTIVITY_TYPE_MOUNTAIN_BIKE_RIDE" | "ACTIVITY_TYPE_NORDIC_SKI" | "ACTIVITY_TYPE_PICKLEBALL" | "ACTIVITY_TYPE_PILATES" | "ACTIVITY_TYPE_RACQUETBALL" | "ACTIVITY_TYPE_RIDE" | "ACTIVITY_TYPE_ROCK_CLIMBING" | "ACTIVITY_TYPE_ROLLER_SKI" | "ACTIVITY_TYPE_ROWING" | "ACTIVITY_TYPE_RUN" | "ACTIVITY_TYPE_SAIL" | "ACTIVITY_TYPE_SKATEBOARD" | "ACTIVITY_TYPE_SNOWBOARD" | "ACTIVITY_TYPE_SNOWSHOE" | "ACTIVITY_TYPE_SOCCER" | "ACTIVITY_TYPE_SQUASH" | "ACTIVITY_TYPE_STAIR_STEPPER" | "ACTIVITY_TYPE_STAND_UP_PADDLING" | "ACTIVITY_TYPE_SURFING" | "ACTIVITY_TYPE_SWIM" | "ACTIVITY_TYPE_TABLE_TENNIS" | "ACTIVITY_TYPE_TENNIS" | "ACTIVITY_TYPE_TRAIL_RUN" | "ACTIVITY_TYPE_VELOMOBILE" | "ACTIVITY_TYPE_VIRTUAL_RIDE" | "ACTIVITY_TYPE_VIRTUAL_ROW" | "ACTIVITY_TYPE_VIRTUAL_RUN" | "ACTIVITY_TYPE_WALK" | "ACTIVITY_TYPE_WEIGHT_TRAINING" | "ACTIVITY_TYPE_WHEELCHAIR" | "ACTIVITY_TYPE_WINDSURF" | "ACTIVITY_TYPE_WORKOUT" | "ACTIVITY_TYPE_YOGA";
            /** Format: date-time */
            startTime?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "PIPELINE_RUN_STATUS_UNSPECIFIED" | "PIPELINE_RUN_STATUS_RUNNING" | "PIPELINE_RUN_STATUS_SYNCED" | "PIPELINE_RUN_STATUS_PARTIAL" | "PIPELINE_RUN_STATUS_FAILED" | "PIPELINE_RUN_STATUS_PENDING" | "PIPELINE_RUN_STATUS_SKIPPED" | "PIPELINE_RUN_STATUS_ARCHIVED" | "PIPELINE_RUN_STATUS_TIER_BLOCKED" | "PIPELINE_RUN_STATUS_CANCELLED" | "PIPELINE_RUN_STATUS_SYNCED_WITH_PENDING";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            boosters?: components["schemas"]["BoosterExecution"][];
            destinations?: components["schemas"]["DestinationOutcome"][];
            statusMessage?: string;
            pendingInputId?: string;
            originalPayloadUri?: string;
            enrichedEventUri?: string;
            /**
             * @description IDs of non-blocking PendingInputs still awaiting user input for this run.
             *      Cleared as each one is resolved; when empty the status transitions to SYNCED.
             */
            nonBlockingPendingInputIds?: string[];
            /**
             * @description Unified record of every step in a pipeline run — source, parse, gate,
             *      enricher batch, router, and per-destination uploaders.
             *      boosters[] is preserved for existing documents; new clients should prefer steps[].
             */
            steps?: components["schemas"]["ExecutionStep"][];
            /**
             * @description Owning user id. Not persisted on the per-user run documents (it is implied by
             *      the document path); populated by the admin cross-user listing so callers can
             *      act on the run. Empty on the user-facing API.
             */
            userId?: string;
        };
        RecentPipelineRunCounts: {
            /** Format: int32 */
            success?: number;
            /** Format: int32 */
            failed?: number;
            /** Format: int32 */
            started?: number;
        };
        RepostActivityAdminRequest: {
            id?: string;
            activityId?: string;
            /** @description "missed-destination" | "retry-destination" | "full-pipeline" */
            mode?: string;
            destination?: string;
        };
        ResolvePendingInputAdminRequest: {
            id?: string;
            inputId?: string;
        };
        /** @description ----------------------- User Actions ----------------------- */
        SetIntegrationEnabledAdminRequest: {
            id?: string;
            provider?: string;
            enabled?: boolean;
        };
        /** @description The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors). */
        Status: {
            /**
             * Format: int32
             * @description The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
             */
            code?: number;
            /** @description A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client. */
            message?: string;
            /** @description A list of messages that carry the error details.  There is a common set of message types for APIs to use. */
            details?: components["schemas"]["GoogleProtobufAny"][];
        };
        /** @description SubscriptionState tracks the user's billing info, decoupled from core profile. */
        SubscriptionState: {
            userId?: string;
            /** @description Stripe customer ID for billing */
            stripeCustomerId?: string;
            stripeSubscriptionId?: string;
            /**
             * Format: date-time
             * @description Athlete trial end date (null = no trial)
             */
            trialEndsAt?: string;
            /**
             * Format: enum
             * @description The actual purchased tier (free users won't have this record or it will be free)
             * @enum {string}
             */
            subscriptionTier?: "USER_TIER_UNSPECIFIED" | "USER_TIER_HOBBYIST" | "USER_TIER_ATHLETE";
            /** Format: date-time */
            currentPeriodStart?: string;
            /** Format: date-time */
            currentPeriodEnd?: string;
            cancelAtPeriodEnd?: boolean;
            status?: string;
        };
        UpdatePipelineAdminRequest: {
            id?: string;
            pipelineId?: string;
            pipeline?: components["schemas"]["PipelineConfig"];
        };
        UpdateUserAdminRequest: {
            id?: string;
            accessEnabled?: boolean;
            /**
             * Format: enum
             * @enum {string}
             */
            tier?: "USER_TIER_UNSPECIFIED" | "USER_TIER_HOBBYIST" | "USER_TIER_ATHLETE";
            isAdmin?: boolean;
            displayName?: string;
        };
        UserIdAdminRequest: {
            id?: string;
        };
        /**
         * @description UserProfile represents the core user identity and preferences,
         *      cleanly separated from billing and integrations.
         */
        UserProfile: {
            userId?: string;
            /** Format: date-time */
            createdAt?: string;
            fcmTokens?: string[];
            /**
             * Format: enum
             * @enum {string}
             */
            tier?: "USER_TIER_UNSPECIFIED" | "USER_TIER_HOBBYIST" | "USER_TIER_ATHLETE";
            isAdmin?: boolean;
            /**
             * Format: int32
             * @description Monthly sync tracking
             */
            syncCountThisMonth?: number;
            /** Format: date-time */
            syncCountResetAt?: string;
            /** Format: int32 */
            preventedSyncCount?: number;
            /** @description Waitlist gate - false until admin enables access */
            accessEnabled?: boolean;
            /** @description User's push notification preferences */
            notificationPreferences?: components["schemas"]["NotificationPreferences"];
            /** Format: date-time */
            trialEndsAt?: string;
            email?: string;
            displayName?: string;
            /**
             * Format: int32
             * @description Streak aggregates — written by streak-tracker enricher rollup on every activity sync.
             *      A "streak day" is any calendar day with at least one qualifying activity.
             *      Optional; absent means not yet computed.
             */
            currentStreakDays?: number;
            /** Format: int32 */
            longestStreakDays?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminGatewayService_ListAuditLog: {
        parameters: {
            query?: {
                targetUserId?: string;
                limit?: number;
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAuditLogAdminResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_ListPipelineRuns: {
        parameters: {
            query?: {
                status?: string;
                source?: string;
                userId?: string;
                limit?: number;
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPipelineRunsAdminResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_ListAllPipelines: {
        parameters: {
            query?: {
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAllPipelinesAdminResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_GetStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAdminStatsResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_ListUsers: {
        parameters: {
            query?: {
                limit?: number;
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsersAdminResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_GetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetail"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_UpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetail"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_DeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_RepostActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                activityId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepostActivityAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_GetUserBilling: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserBilling"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_CancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserIdAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_CreateBillingPortalSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBillingPortalAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateBillingPortalAdminResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_StartTrial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserIdAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_DeleteIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_SetIntegrationEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetIntegrationEnabledAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_ListPendingInputs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPendingInputsAdminResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_ResolvePendingInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                inputId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolvePendingInputAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_GetPipelineRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRun"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_CancelPipelineRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelPipelineRunAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_GetPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                pipelineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineConfig"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_UpdatePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                pipelineId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePipelineAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineConfig"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_DeletePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                pipelineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_SendPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserIdAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_SendVerificationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserIdAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_DeleteUserData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                dataType: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
}
