/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pipeline-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminGatewayService_ListPipelineRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ===================== Pipeline Management ===================== */
        get: operations["AdminGatewayService_ListAllPipelines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ===================== Platform Stats ===================== */
        get: operations["AdminGatewayService_GetStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ===================== User Management ===================== */
        get: operations["AdminGatewayService_ListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminGatewayService_GetUser"];
        put: operations["AdminGatewayService_UpdateUser"];
        post?: never;
        delete: operations["AdminGatewayService_DeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/{dataType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminGatewayService_DeleteUserData"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminEmptyResponse: Record<string, never>;
        BoosterExecution: {
            providerName?: string;
            status?: string;
            durationMs?: string;
            metadata?: {
                [key: string]: string;
            };
            error?: string;
        };
        DestinationConfig: {
            config?: {
                [key: string]: string;
            };
            excludedEnrichers?: string[];
        };
        DestinationOutcome: {
            /** Format: enum */
            destination?: number;
            /** Format: enum */
            status?: number;
            externalId?: string;
            error?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        EnricherConfig: {
            /** Format: enum */
            providerType?: number;
            typedConfig?: {
                [key: string]: string;
            };
        };
        GetAdminStatsResponse: {
            /** Format: int32 */
            totalUsers?: number;
            /** Format: int32 */
            athleteUsers?: number;
            /** Format: int32 */
            adminUsers?: number;
            /** Format: int32 */
            totalSyncsThisMonth?: number;
            recentExecutions?: components["schemas"]["RecentPipelineRunCounts"];
        };
        /** @description Contains an arbitrary serialized message along with a @type that describes the type of the serialized message. */
        GoogleProtobufAny: {
            /** @description The type of the serialized message. */
            "@type"?: string;
        } & {
            [key: string]: unknown;
        };
        ListAllPipelinesAdminResponse: {
            pipelines?: components["schemas"]["PipelineConfig"][];
        };
        ListPipelineRunsAdminResponse: {
            runs?: components["schemas"]["PipelineRun"][];
            nextPageToken?: string;
        };
        ListUsersAdminResponse: {
            users?: components["schemas"]["UserProfile"][];
            nextPageToken?: string;
        };
        NotificationPreferences: {
            notifyPendingInput?: boolean;
            notifyPipelineSuccess?: boolean;
            notifyPipelineFailure?: boolean;
        };
        PipelineConfig: {
            id?: string;
            source?: string;
            enrichers?: components["schemas"]["EnricherConfig"][];
            destinations?: number[];
            name?: string;
            disabled?: boolean;
            sourceConfig?: {
                [key: string]: string;
            };
            destinationConfigs?: {
                [key: string]: components["schemas"]["DestinationConfig"];
            };
        };
        PipelineRun: {
            id?: string;
            pipelineId?: string;
            activityId?: string;
            source?: string;
            sourceActivityId?: string;
            title?: string;
            description?: string;
            /** Format: enum */
            type?: number;
            /** Format: date-time */
            startTime?: string;
            /** Format: enum */
            status?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            boosters?: components["schemas"]["BoosterExecution"][];
            destinations?: components["schemas"]["DestinationOutcome"][];
            statusMessage?: string;
            pendingInputId?: string;
            originalPayloadUri?: string;
            enrichedEventUri?: string;
        };
        RecentPipelineRunCounts: {
            /** Format: int32 */
            success?: number;
            /** Format: int32 */
            failed?: number;
            /** Format: int32 */
            started?: number;
        };
        /** @description The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors). */
        Status: {
            /**
             * Format: int32
             * @description The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
             */
            code?: number;
            /** @description A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client. */
            message?: string;
            /** @description A list of messages that carry the error details.  There is a common set of message types for APIs to use. */
            details?: components["schemas"]["GoogleProtobufAny"][];
        };
        UpdateUserAdminRequest: {
            id?: string;
            accessEnabled?: boolean;
        };
        /**
         * @description UserProfile represents the core user identity and preferences,
         *      cleanly separated from billing and integrations.
         */
        UserProfile: {
            userId?: string;
            /** Format: date-time */
            createdAt?: string;
            fcmTokens?: string[];
            /** Format: enum */
            tier?: number;
            isAdmin?: boolean;
            /**
             * Format: int32
             * @description Monthly sync tracking
             */
            syncCountThisMonth?: number;
            /** Format: date-time */
            syncCountResetAt?: string;
            /** Format: int32 */
            preventedSyncCount?: number;
            /** @description Waitlist gate - false until admin enables access */
            accessEnabled?: boolean;
            /** @description User's push notification preferences */
            notificationPreferences?: components["schemas"]["NotificationPreferences"];
            /** Format: date-time */
            trialEndsAt?: string;
            email?: string;
            displayName?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminGatewayService_ListPipelineRuns: {
        parameters: {
            query?: {
                status?: string;
                source?: string;
                userId?: string;
                limit?: number;
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPipelineRunsAdminResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_ListAllPipelines: {
        parameters: {
            query?: {
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAllPipelinesAdminResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_GetStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAdminStatsResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_ListUsers: {
        parameters: {
            query?: {
                limit?: number;
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsersAdminResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_GetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_UpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserAdminRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_DeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    AdminGatewayService_DeleteUserData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                dataType: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEmptyResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
}
