// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: models/notification/notification.proto

/* eslint-disable */

export const protobufPackage = "fitglue.models.notification";

export enum NotificationType {
  NOTIFICATION_TYPE_UNSPECIFIED = 0,
  NOTIFICATION_TYPE_PENDING_INPUT = 1,
  NOTIFICATION_TYPE_PIPELINE_SUCCESS = 2,
  NOTIFICATION_TYPE_PIPELINE_FAILURE = 3,
  NOTIFICATION_TYPE_CONNECTION_ACTION = 4,
  NOTIFICATION_TYPE_SHOWCASE_ROUNDUP = 5,
  NOTIFICATION_TYPE_PIPELINE_CANCELLED = 6,
  UNRECOGNIZED = -1,
}

/**
 * NotificationRequest is published to topic-notification by any service that wants
 * to notify a user. The notification service decides which channels to use based on
 * the user's per-type, per-channel preferences.
 */
export interface NotificationRequest {
  userId: string;
  type: NotificationType;
  title: string;
  body: string;
  /** Arbitrary key-value pairs forwarded to the client (e.g. activity_id for deep-linking). */
  data: { [key: string]: string };
}

export interface NotificationRequest_DataEntry {
  key: string;
  value: string;
}
